class Autogenerated {
  Result? result;

  Autogenerated({this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result = json['result'] != null ? Result.fromJson(json['result']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    return data;
  }
}

class Result {
  Status? status;
  List<ResultListCat>? resultListCat;

  Result({this.status, this.resultListCat});

  Result.fromJson(Map<String, dynamic> json) {
    status = json['status'] != null ? Status.fromJson(json['status']) : null;
    if (json['resultList'] != null) {
      resultListCat = <ResultListCat>[];
      json['resultList'].forEach((v) {
        resultListCat!.add(ResultListCat.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (status != null) {
      data['status'] = status!.toJson();
    }
    if (resultListCat != null) {
      data['resultList'] = resultListCat!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Status {
  int? code;
  String? data;
  String? executionTime;
  String? requestTime;
  String? requestId;
  String? endpoint;
  String? apiVersion;
  String? functionsVersion;
  String? la;
  int? pmu;
  int? mu;

  Status({
    this.code,
    this.data,
    this.executionTime,
    this.requestTime,
    this.requestId,
    this.endpoint,
    this.apiVersion,
    this.functionsVersion,
    this.la,
    this.pmu,
    this.mu,
  });

  Status.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'];
    executionTime = json['executionTime'];
    requestTime = json['requestTime'];
    requestId = json['requestId'];
    endpoint = json['endpoint'];
    apiVersion = json['apiVersion'];
    functionsVersion = json['functionsVersion'];
    la = json['la'];
    pmu = json['pmu'];
    mu = json['mu'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['code'] = code;
    data['data'] = this.data;
    data['executionTime'] = executionTime;
    data['requestTime'] = requestTime;
    data['requestId'] = requestId;
    data['endpoint'] = endpoint;
    data['apiVersion'] = apiVersion;
    data['functionsVersion'] = functionsVersion;
    data['la'] = la;
    data['pmu'] = pmu;
    data['mu'] = mu;
    return data;
  }
}

class ResultListCat {
  String? name;
  int? id;
  List<SubCategory>? subCategories;
  String? selectedSubCategory; // Add this field

  ResultListCat({
    this.name,
    this.id,
    this.subCategories,
    this.selectedSubCategory,
  });

  ResultListCat.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
    if (json['list'] != null) {
      subCategories = <SubCategory>[];
      json['list'].forEach((v) {
        subCategories!.add(SubCategory.fromJson(v));
      });
    }
    // Initialize selectedSubCategory if needed
    selectedSubCategory = subCategories?.first.name; // Or a default value
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name'] = name;
    data['id'] = id;
    if (subCategories != null) {
      data['list'] = subCategories!.map((v) => v.toJson()).toList();
    }
    data['selectedSubCategory'] = selectedSubCategory;
    return data;
  }
}

class SubCategory {
  String? name;
  int? id;

  SubCategory({this.name, this.id});

  SubCategory.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name'] = name;
    data['id'] = id;
    return data;
  }
}
