import 'dart:developer';

import 'package:e_comerece/app_api/link_api.dart';
import 'package:e_comerece/core/class/statusrequest.dart';
import 'package:e_comerece/core/constant/routesname.dart';
import 'package:e_comerece/core/funcations/handle_paging_response.dart';
import 'package:e_comerece/core/funcations/handlingdata.dart';
import 'package:e_comerece/core/funcations/loading_dialog.dart';
import 'package:e_comerece/core/loacallization/translate_data.dart';
import 'package:e_comerece/core/shared/image_manger/Image_manager_controller.dart';
import 'package:e_comerece/data/datasource/remote/aliexpriess/category_data.dart';
import 'package:e_comerece/data/datasource/remote/aliexpriess/hotproductssdata.dart';
import 'package:e_comerece/data/datasource/remote/aliexpriess/searchtext_data.dart';
import 'package:e_comerece/data/datasource/remote/api_cash/get_cash_data.dart';
import 'package:e_comerece/data/datasource/remote/api_cash/insert_cash_data.dart';
import 'package:e_comerece/data/datasource/remote/upload_to_cloudinary.dart';
import 'package:e_comerece/data/model/aliexpriess_model/category_model.dart';
import 'package:e_comerece/data/model/aliexpriess_model/hotproductmodel.dart';
import 'package:e_comerece/data/model/aliexpriess_model/searshtextmodel.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

abstract class AliexpriseHomeController extends GetxController {
  Future<void> fetchHomePageData();
  Future<void> searshText({required String keyWord});
  // Future<void> fetchOnrefresh();
  Future<void> fetchCategories();
  Future<void> fetchProducts({required bool isLoadMore});
  void loadMore();
  void loadMoreSearch(String lang);
  void onTapSearch({required String keyWord});
  void onChangeSearch(String value);
  void goTofavorite();
  void gotoditels({
    required int id,
    required String lang,
    required String title,
  });
  void goToSearchByimage();
  void gotoshearchname(String nameCat, int categoryId);
  void indexchange(int index);
}

class HomePageControllerImpl extends AliexpriseHomeController {
  CategoryData categoryData = CategoryData(Get.find());
  HotProductsData hotProductsData = HotProductsData(Get.find());
  SearchtextData searchtextData = SearchtextData(Get.find());
  InsertCashData insertCashData = InsertCashData(Get.find());
  GetCashData getCashData = GetCashData(Get.find());

  Statusrequest statusrequest = Statusrequest.none;
  Statusrequest statusrequestcat = Statusrequest.none;
  Statusrequest statusrequestsearch = Statusrequest.none;
  Statusrequest statusrequestHotProducts = Statusrequest.none;
  TextEditingController searchController = TextEditingController();

  List<ResultListCat> categories = [];
  List<ResultListHotprosuct> hotProducts = [];
  List<ResultListSearshTextModel> searchProducts = [];

  int pageIndex = 0;
  int pageIndexSearch = 0;
  FocusNode focusNode = FocusNode();
  bool isLoading = false;

  bool hasMore = true;
  bool hasMoresearch = true;

  bool isSearch = false;
  bool showClose = false;

  int currentIndex = 0;

  @override
  void onInit() {
    super.onInit();
    fetchHomePageData();
  }

  @override
  fetchCategories() async {
    statusrequestcat = Statusrequest.loading;
    log("start fetch categories=====================");
    cashkey(String q) => 'categories:alexpress:${enOrAr()}';
    // update();
    try {
      final cacheResponse = await getCashData.getCash(
        query: cashkey('categories:alexpress'),
        platform: "aliexpress",
      );
      log("cacheResponse===================== ${cacheResponse["status"]}");
      if (cacheResponse["status"] == "success") {
        log('Loaded categories from cache server');
        final categoryResponse = cacheResponse["data"];
        statusrequestcat = handlingData(categoryResponse);
        if (statusrequestcat == Statusrequest.success) {
          if (categoryResponse is Map &&
              categoryResponse['result']?['status']?['code'] == 200) {
            Autogenerated autogenerated = Autogenerated.fromJson(
              categoryResponse as Map<String, dynamic>,
            );

            if (autogenerated.result != null &&
                autogenerated.result!.resultListCat != null) {
              List<ResultListCat> mainCategories =
                  autogenerated.result!.resultListCat!;

              categories.assignAll(mainCategories);
            }
          }
        }
      } else {
        log('No cache found for categories, fetching from API');
        final categoryResponse = await categoryData.getData();
        statusrequestcat = handlingData(categoryResponse);
        if (statusrequestcat == Statusrequest.success) {
          if (categoryResponse is Map &&
              categoryResponse['result']?['status']?['code'] == 200) {
            Autogenerated autogenerated = Autogenerated.fromJson(
              categoryResponse as Map<String, dynamic>,
            );

            if (autogenerated.result != null &&
                autogenerated.result!.resultListCat != null) {
              List<ResultListCat> mainCategories =
                  autogenerated.result!.resultListCat!;

              categories.assignAll(mainCategories);
              insertCashData.insertCash(
                query: cashkey('categories:alexpress'),
                platform: "aliexpress",
                data: categoryResponse,
                ttlHours: "24",
              );
            }
          }
        }
      }
    } catch (e) {
      log('Error fetching categories: $e');
    }
    // update();
  }

  @override
  fetchProducts({isLoadMore = false}) async {
    cashkey(String q, int p) => 'homeproduct:alexpress:$q:page=$p ${enOrAr()}';

    if (isLoadMore) {
      if (isLoading || !hasMore) return;
      isLoading = true;
    } else {
      statusrequestHotProducts = Statusrequest.loading;
      pageIndex = 1;
      hotProducts.clear();
      hasMore = true;
    }
    update();
    try {
      final cashe = await getCashData.getCash(
        query: cashkey("", pageIndex),
        platform: "aliexpress",
      );
      if (cashe["status"] == "success") {
        log("get product from aliexpress cache server=====================");
        final hotProductsResponse = cashe["data"];
        final status = handlingData(hotProductsResponse);
        if (status == Statusrequest.success) {
          if (handle200(hotProductsResponse)) {
            var hotProductModel = HotProductModel.fromJson(hotProductsResponse);

            if (hotProductModel.result!.resultListHotprosuct!.isEmpty) {
              hasMore = false;
            } else {
              hotProducts.addAll(hotProductModel.result!.resultListHotprosuct!);
              pageIndex++;
            }
            if (!isLoadMore) statusrequestHotProducts = Statusrequest.success;
          }
        } else {
          if (!isLoadMore) {
            statusrequestHotProducts =
                status as Statusrequest? ?? Statusrequest.failuer;
          }
          hasMore = false;
        }
      } else {
        log("get product from aliexpress api=====================");
        final hotProductsResponse = await hotProductsData.getData(pageIndex);

        final status = handlingData(hotProductsResponse);
        if (status == Statusrequest.success) {
          if (handle200(hotProductsResponse)) {
            var hotProductModel = HotProductModel.fromJson(hotProductsResponse);

            if (hotProductModel.result!.resultListHotprosuct!.isEmpty) {
              hasMore = false;
            } else {
              hotProducts.addAll(hotProductModel.result!.resultListHotprosuct!);
              insertCashData.insertCash(
                query: cashkey("", pageIndex),
                platform: "aliexpress",
                data: hotProductsResponse,
                ttlHours: "24",
              );

              pageIndex++;
            }
            if (!isLoadMore) statusrequestHotProducts = Statusrequest.success;
          } else if (handle205(hotProductsResponse, pageIndex)) {
            hasMore = false;
            statusrequestHotProducts = Statusrequest.noDataPageindex;
            custSnackBarNoMore();
          }
        } else {
          if (!isLoadMore) {
            statusrequestHotProducts =
                status as Statusrequest? ?? Statusrequest.failuer;
          }
          hasMore = false;
        }
      }
    } catch (e) {
      log('Error fetching products: $e');
    }

    isLoading = false;
    update();
  }

  @override
  void loadMore() {
    fetchProducts(isLoadMore: true);
  }

  @override
  fetchHomePageData({bool isrefresh = false}) async {
    statusrequest = Statusrequest.loading;
    update();
    if (isrefresh == false) {
      await fetchCategories();
      await fetchProducts();
      // await Future.wait([fetchCategories(), fetchProducts()]);
    } else {
      await Future.wait({fetchProducts()});
    }
    if (statusrequest == Statusrequest.loading) {
      statusrequest = Statusrequest.success;
    }
    update();
  }

  @override
  gotoditels({required id, required lang, required title}) {
    Get.toNamed(
      AppRoutesname.detelspage,
      arguments: {"product_id": id, "lang": lang, "title": title},
    );
  }

  @override
  gotoshearchname(nameCat, categoryId) {
    Get.toNamed(
      AppRoutesname.shearchname,
      arguments: {
        'namecat': nameCat,
        "categoryId": categoryId,
        "categorymodel": categories,
      },
    );
  }

  @override
  searshText({required String keyWord, bool isLoadMore = false}) async {
    cashkey(String q, int p) => 'search:aliexpress:$q:page=$p ${enOrAr()}';
    if (isLoadMore) {
      if (isLoading || !hasMoresearch) return;
      isLoading = true;
    } else {
      statusrequestsearch = Statusrequest.loading;
      pageIndexSearch = 1;
      searchProducts.clear();
      hasMoresearch = true;
    }
    update();

    try {
      final cashe = await getCashData.getCash(
        query: cashkey(searchController.text, pageIndex),
        platform: "aliexpress",
      );
      if (cashe["status"] == "success") {
        log("get search from aliexpress cache server=====================");
        final response = cashe["data"];
        statusrequestsearch = handlingData(response);
        if (statusrequestsearch == Statusrequest.success) {
          if (handle200(response)) {
            final model = SearshTextModel.fromJson(response);
            final List<ResultListSearshTextModel> iterable =
                model.resultSearshTextModel!.resultListSearshTextModel!;

            if (iterable.isEmpty) {
              hasMoresearch = false;
              statusrequestsearch = Statusrequest.noData;
            } else {
              searchProducts.addAll(iterable);
              pageIndexSearch++;
            }
          } else {
            hasMoresearch = false;
            statusrequestsearch = Statusrequest.noData;
          }
        }
      } else {
        log("get search from aliexpress api=====================");
        final response = await searchtextData.getData(
          lang: detectLangFromQuery(searchController.text),
          keyWord: keyWord,
          pageindex: pageIndexSearch,
        );

        statusrequestsearch = handlingData(response);
        if (statusrequestsearch == Statusrequest.success) {
          if (handle200(response)) {
            final model = SearshTextModel.fromJson(response);
            final List<ResultListSearshTextModel> iterable =
                model.resultSearshTextModel!.resultListSearshTextModel!;

            if (iterable.isEmpty) {
              hasMoresearch = false;
              statusrequestsearch = Statusrequest.noData;
            } else {
              searchProducts.addAll(iterable);
              insertCashData.insertCash(
                query: cashkey(searchController.text, pageIndexSearch),
                platform: "aliexpress",
                data: response,
                ttlHours: "24",
              );
              pageIndexSearch++;
            }
          } else if (handle205(response, pageIndexSearch)) {
            hasMoresearch = false;
            statusrequestsearch = Statusrequest.noDataPageindex;
            custSnackBarNoMore();
          } else {
            hasMoresearch = false;
            statusrequestsearch = Statusrequest.noData;
          }
        }
      }
    } catch (e) {
      hasMoresearch = false;
      statusrequestsearch = Statusrequest.failuer;
    } finally {
      if (isLoadMore) isLoading = false;
      update();
    }
  }

  @override
  loadMoreSearch(lang) {
    searshText(keyWord: searchController.text, isLoadMore: true);
  }

  @override
  onChangeSearch(String val) {
    if (val == "") {
      isSearch = false;
      focusNode.unfocus();
      update();
    }
  }

  @override
  onTapSearch({required keyWord}) {
    isSearch = true;

    searshText(keyWord: keyWord);
    update();
  }

  whenstartSearch(String q) async {
    if (q != "") {
      showClose = true;
      update();
    } else {
      focusNode.unfocus();
      showClose = false;
    }
  }

  onCloseSearch() {
    if (isSearch) {
      isSearch = false;
      focusNode.unfocus();
      searchController.clear();
      update();
      showClose = false;
      // update(['initShow']);
    } else {
      searchController.clear();
      focusNode.unfocus();
      showClose = false;
      // update(['initShow']);
    }
  }

  @override
  goTofavorite() {
    Get.toNamed(
      AppRoutesname.favoritealiexpress,
      arguments: {'platform': "Aliexpress"},
    );
  }

  @override
  indexchange(int index) {
    currentIndex = index;
    update(["index"]);
  }

  @override
  goToSearchByimage() {
    Get.put(ImageManagerController()).pickImage().then((image) {
      if (image.path != '') {
        if (!Get.isDialogOpen!) {
          loadingDialog();
        }
      }
      uploadToCloudinary(
            filePath: image.path,
            cloudName: Appapi.cloudName,
            uploadPreset: Appapi.uploadPreset,
          )
          .then((url) {
            log("url $url");
            if (Get.isDialogOpen ?? false) Get.back();
            if (url != null) {
              Get.toNamed(
                AppRoutesname.searchByimagealiexpress,
                arguments: {'url': url, 'image': image},
              );
            } else {}
          })
          .catchError((err) {});
    });
  }
}
