import 'package:e_comerece/core/class/statusrequest.dart';
import 'package:e_comerece/core/constant/routesname.dart';
import 'package:e_comerece/core/funcations/handlingdata.dart';
import 'package:e_comerece/data/datasource/remote/aliexpriess/category_data.dart';
import 'package:e_comerece/data/datasource/remote/aliexpriess/hotproductssdata.dart';
import 'package:e_comerece/data/datasource/remote/aliexpriess/searchtext_data.dart';
import 'package:e_comerece/data/model/category_model.dart';
import 'package:e_comerece/data/model/hotproductmodel.dart';
import 'package:e_comerece/data/model/searshtextmodel.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

abstract class HomePageController extends GetxController {
  Future<void> fetchHomePageData();
  void loadMore();
  void loadMoreSearch(String lang);
  void onTapSearch({required String keyWord, required String lang});
  void onChangeSearch(String value);
  void goTofavorite();
  void gotoditels({required int id, required String lang});
  void gotoshearchname(String nameCat, int categoryId);
  Future<void> searshText({required String keyWord, required String lang});
  Future<void> fetchOnrefresh();
  Future<void> fetchCategories();
  Future<void> fetchProducts({required bool isLoadMore});
}

class HomePageControllerImpl extends HomePageController {
  CategoryData categoryData = CategoryData(Get.find());
  HotProductsData hotProductsData = HotProductsData(Get.find());
  SearchtextData searchtextData = SearchtextData(Get.find());

  Statusrequest statusrequest = Statusrequest.none;
  Statusrequest statusrequestHotProducts = Statusrequest.none;
  TextEditingController searchController = TextEditingController();

  List<ResultListCat> categories = [];
  List<ResultListHotprosuct> hotProducts = [];
  List<ResultListSearshTextModel> searchProducts = [];

  int pageIndex = 0;
  int pageIndexSearch = 0;

  bool isLoading = false;

  bool hasMore = true;
  bool hasMoresearch = true;

  bool isSearch = false;

  @override
  void onInit() {
    super.onInit();
    fetchHomePageData();
  }

  @override
  fetchCategories() async {
    print("fetchCategories");
    var categoryResponse = await categoryData.getData();

    if (categoryResponse is Map &&
        categoryResponse['result']?['status']?['code'] == 200) {
      final responseAsMap = categoryResponse as Map<String, dynamic>;

      Autogenerated autogenerated = Autogenerated.fromJson(responseAsMap);

      if (autogenerated.result != null &&
          autogenerated.result!.resultListCat != null) {
        List<ResultListCat> mainCategories =
            autogenerated.result!.resultListCat!;

        categories.assignAll(mainCategories);
      }
    }
  }

  @override
  fetchProducts({isLoadMore = false}) async {
    print("fetchProducts");
    if (isLoadMore) {
      if (isLoading || !hasMore) return;
      isLoading = true;
    } else {
      statusrequestHotProducts = Statusrequest.loading;
      pageIndex = 1;
      hotProducts.clear();
      hasMore = true;
    }
    update();

    var hotProductsResponse = await hotProductsData.getData(pageIndex);
    var status = handlingData(hotProductsResponse);
    if (hotProductsResponse is Map &&
        hotProductsResponse['result']?['status']['code'] == 200) {
      var hotProductModel = HotProductModel.fromJson(
        hotProductsResponse as Map<String, dynamic>,
      );

      if (hotProductModel.result!.resultListHotprosuct!.isEmpty) {
        hasMore = false;
      } else {
        hotProducts.addAll(hotProductModel.result!.resultListHotprosuct!);
        pageIndex++;
      }
      if (!isLoadMore) statusrequestHotProducts = Statusrequest.success;
    } else {
      if (!isLoadMore) {
        statusrequestHotProducts =
            status as Statusrequest? ?? Statusrequest.failuer;
      }
      hasMore = false;
    }

    isLoading = false;
    update();
  }

  @override
  void loadMore() {
    fetchProducts(isLoadMore: true);
  }

  @override
  fetchHomePageData() async {
    statusrequest = Statusrequest.loading;
    update();
    await Future.wait([fetchCategories(), fetchProducts()]);
    if (statusrequest == Statusrequest.loading) {
      statusrequest = Statusrequest.success;
    }
    update();
  }

  @override
  fetchOnrefresh() async {
    statusrequest = Statusrequest.loading;
    update();

    await Future.wait({fetchProducts()});
    if (statusrequest == Statusrequest.loading) {
      statusrequest = Statusrequest.success;
    }
    update();
  }

  @override
  gotoditels({required id, required lang}) {
    Get.toNamed(
      AppRoutesname.detelspage,
      arguments: {"product_id": id, "lang": lang},
    );
  }

  @override
  gotoshearchname(nameCat, categoryId) {
    Get.toNamed(
      AppRoutesname.shearchname,
      arguments: {
        'namecat': nameCat,
        "categoryId": categoryId,
        "categorymodel": categories,
      },
    );
  }

  @override
  searshText({
    required String keyWord,
    required String lang,
    bool isLoadMore = false,
  }) async {
    if (isLoadMore) {
      if (isLoading || !hasMoresearch) return;
      isLoading = true;
    } else {
      statusrequest = Statusrequest.loading;
      pageIndexSearch = 1;
      searchProducts.clear();
      hasMoresearch = true;
    }
    update();

    try {
      var response = await searchtextData.getData(
        lang: lang,
        keyWord: keyWord,
        pageindex: pageIndexSearch,
      );
      print("response=>$response");

      statusrequest = handlingData(response);

      if (statusrequest == Statusrequest.success &&
          response != null &&
          response['result']['status']['code'] == 200) {
        final model = SearshTextModel.fromJson(
          response as Map<String, dynamic>,
        );
        final List<ResultListSearshTextModel> iterable =
            model.resultSearshTextModel!.resultListSearshTextModel!;

        if (iterable.isEmpty) {
          hasMoresearch = false;
          statusrequest = Statusrequest.noData;

          if (!isLoadMore) {
            searchProducts = [];
          }
        } else {
          searchProducts.addAll(iterable);
          pageIndexSearch++;
          statusrequest = Statusrequest.success;
        }
      } else {
        hasMoresearch = false;
        if (!isLoadMore) searchProducts = [];
        statusrequest = Statusrequest.failuer;
      }
    } catch (e) {
      hasMoresearch = false;
      if (!isLoadMore) searchProducts = [];
      statusrequest = Statusrequest.failuer;
    } finally {
      if (isLoadMore) isLoading = false;
      update();
    }
  }

  @override
  void loadMoreSearch(lang) {
    searshText(keyWord: searchController.text, isLoadMore: true, lang: lang);
  }

  @override
  onChangeSearch(String val) {
    if (val == "") {
      isSearch = false;
    }
    update();
  }

  @override
  onTapSearch({required keyWord, required lang}) {
    isSearch = true;
    searshText(keyWord: keyWord, lang: lang);
    update();
  }

  @override
  goTofavorite() {
    Get.toNamed(
      AppRoutesname.favoritealiexpress,
      arguments: {'platform': "Aliexpress"},
    );
  }
}
