// Strings Keys for Translation
class StringsKeys {
  // Splashscreen Keys
  static const String appName = "appName";
  static const String letsGetStarted = "letsGetStarted";
  static const String alreadyHaveAccount = "alreadyHaveAccount";

  // Exit Dialog Keys
  static const String exitDialogTitle = "exitDialogTitle";
  static const String exitDialogMessage = "exitDialogMessage";
  static const String cancel = "cancel";
  static const String exit = "exit";

  // Login Step One Keys
  static const String emailHint = "emailHint";
  static const String next = "Next";
  static const String orSignInWith = "Orsigninwith";
  static const String google = "google";
  static const String noAccount = "noAccount";
  static const String signUp = "signUp";
  static const String loginTitle = "loginTitle";
  static const String loginBody = "loginBody";
  static const String gotIt = "gotIt";
  static const String error = "error";
  static const String passwordIncorrect = "passwordIncorrect";
  static const String accountNotFound = "accountNotFound";
  static const String createAccount = "createAccount";
  static const String usernameHint = "usernameHint";
  static const String phoneHint = "phoneHint";
  static const String passwordHint = "passwordHint";
  static const String haveAccount = "haveAccount";
  static const String login = "login";
  static const String emailOrPhoneExists = "emailOrPhoneExists";
  static const String resendVerifyCode = "resendVerifyCode";
  static const String verifyCodeTitle = "verifyCodeTitle";
  static const String verifyCodeBody = "verifyCodeBody";
  static const String incorrectCode = "incorrectCode";
  static const String successSignUpTitle = "successSignUpTitle";
  static const String successSignUpBody = "successSignUpBody";
  static const String goToLogin = "goToLogin";
  static const String back = "back";
  static const String hello = "hello";
  static const String notYou = "notYou";
  static const String forgotPassword = "forgotPassword";
  static const String forgotPasswordTitle = "forgotPasswordTitle";
  static const String forgotPasswordBody = "forgotPasswordBody";
  static const String check = "check";
  static const String resetPasswordTitle = "resetPasswordTitle";
  static const String resetPasswordBody = "resetPasswordBody";
  static const String confirmPasswordHint = "confirmPasswordHint";
  static const String save = "save";
  static const String passwordNotMatch = "passwordNotMatch";
  static const String successResetPasswordTitle = "successResetPasswordTitle";
  static const String successResetPasswordBody = "successResetPasswordBody";

  // Verification Method Keys
  static const String chooseVerificationMethod = "chooseVerificationMethod";
  static const String verificationMethodBody = "verificationMethodBody";
  static const String sendViaSms = "sendViaSms";
  static const String sendViaSmsDesc = "sendViaSmsDesc";
  static const String sendViaEmail = "sendViaEmail";
  static const String sendViaEmailDesc = "sendViaEmailDesc";
  static const String smsSendFailed = "smsSendFailed";
  static const String tryAnotherMethod = "tryAnotherMethod";
  static const String trySmsAgain = "trySmsAgain";
  static const String tryWithEmail = "tryWithEmail";
  static const String emailOrPhoneHint = "emailOrPhoneHint";
  static const String verifyViaEmail = "verifyViaEmail";
  static const String verifyViaPhone = "verifyViaPhone";
  static const String codeSentToPhone = "codeSentToPhone";
  static const String codeSentToEmail = "codeSentToEmail";

  static const String all = "all";
  static const String productFromAliexpress = "productFromAliexpress";
  static const String loadMoreAliexpress = "loadMoreAliexpress";
  static const String showLessAliexpress = "showLessAliexpress";
  static const String productFromAlibaba = "productFromAlibaba";
  static const String loadMoreAlibaba = "loadMoreAlibaba";
  static const String showLessAlibaba = "showLessAlibaba";
  static const String productFromAmazon = "productFromAmazon";
  static const String loadMoreAmazon = "loadMoreAmazon";
  static const String showLessAmazon = "showLessAmazon";
  static const String productFromShein = "productFromShein";
  static const String loadMoreShein = "loadMoreShein";
  static const String showLessShein = "showLessShein";
  static const String bestFromAliexpress = "bestFromAliexpress";
  static const String bestFromAlibaba = "bestFromAlibaba";
  static const String hotDealsFromAmazon = "hotDealsFromAmazon";
  static const String trendingProductsFromShein = "trendingProductsFromShein";
  static const String sales = "sales";
  static const String searchHint = "searchHint";
  static const String searchPlatforms = "searchPlatforms";
  static const String searchForProducts = "searchForProducts";
  static const String cantBeEmpty = "cantBeEmpty";
  static const String notValidUsername = "notValidUsername";
  static const String notValidEmail = "notValidEmail";
  static const String notValidEmailOrPhone = "notValidEmailOrPhone";
  static const String cantBeLessThan = "cantBeLessThan";
  static const String cantBeLargerThan = "cantBeLargerThan";
  static const String disableNotifications = "disableNotifications";
  static const String historyChats = "historyChats";
  static const String address = "address";
  static const String aboutUs = "aboutUs";
  static const String contactUs = "contactUs";
  static const String logout = "logout";
  static const String language = "language";
  static const String deliveryAddress = "deliveryAddress";
  static const String addAddress = "addAddress";
  static const String deleteAddress = "deleteAddress";
  static const String deleteAddressConfirmation = "deleteAddressConfirmation";
  static const String delete = "delete";

  static const String addressTitle = "addressTitle";
  static const String city = "city";
  static const String street = "street";
  static const String floor = "floor";
  static const String buildingNumber = "buildingNumber";
  static const String apartment = "apartment";
  static const String phone = "phone";
  static const String addressLabel = "addressLabel";
  static const String yourName = "yourName";
  static const String yourMessage = "yourMessage";
  static const String messages = "messages";
  static const String favoritesAll = "favoritesAll";
  static const String couponCode = "couponCode";
  static const String discountCoupon = "discountCoupon";
  static const String apply = "apply";
  static const String total = "total";
  static const String checkout = "checkout";
  static const String howCouponWorks = "howCouponWorks";
  static const String couponExplanation = "couponExplanation";
  static const String okay = "okay";
  static const String orders = "orders";
  static const String orderDetailsTitle = "orderDetailsTitle";
  static const String products = "products";
  static const String orderStatusPending = "orderStatusPending";
  static const String orderStatusActionRequired = "orderStatusActionRequired";
  static const String orderStatusProcessing = "orderStatusProcessing";
  static const String orderStatusShipped = "orderStatusShipped";
  static const String orderStatusCompleted = "orderStatusCompleted";
  static const String orderStatusCancelled = "orderStatusCancelled";
  static const String orderTrackingTitle = "orderTrackingTitle";
  static const String orderStatusCancelledTitle = "orderStatusCancelledTitle";
  static const String orderCancelledBody = "orderCancelledBody";
  static const String orderPrefix = "orderPrefix";
  static const String unknownStatus = "unknownStatus";
  static const String notAvailable = "notAvailable";
  static const String subtotal = "subtotal";
  static const String discount = "discount";
  static const String shipping = "shipping";
  static const String totalAmount = "totalAmount";
  static const String orderInformation = "orderInformation";
  static const String orderIdLabel = "orderIdLabel";
  static const String orderDateLabel = "orderDateLabel";
  static const String orderStatusLabel = "orderStatusLabel";
  static const String paymentMethodLabel = "paymentMethodLabel";
  static const String paymentStatusLabel = "paymentStatusLabel";
  static const String visa = "visa";
  static const String mastercard = "mastercard";
  static const String cash = "cash";
  static const String paid = "paid";
  static const String pendingPayment = "pendingPayment";
  static const String failedStatus = "failedStatus";
  static const String notDefined = "notDefined";
  static const String orderSummary = "orderSummary";
  static const String changeLanguage = "changeLanguage";
  static const String cart = "cart";
  static const String alert = "alert";
  static const String maxQuantityReached = "maxQuantityReached";
  static const String couponEmpty = "couponEmpty";
  static const String couponAppliedSuccess = "couponAppliedSuccess";
  static const String couponUsedOrExpired = "couponUsedOrExpired";
  static const String couponInvalid = "couponInvalid";
  static const String cartEmpty = "cartEmpty";
  static const String couponSpecificPlatformError =
      "couponSpecificPlatformError";
  static const String favoritesPlatform = "favoritesPlatform";
  static const String startPriceRandom = "startPriceRandom";
  static const String startPriceLabel = "startPriceLabel";
  static const String endPriceRandom = "endPriceRandom";
  static const String endPriceLabel = "endPriceLabel";
  static const String priceFilterNote = "priceFilterNote";
  static const String startPrice = "startPrice";
  static const String endPrice = "endPrice";
  static const String change = "change";
  static const String amazonTitle = "amazonTitle";
  static const String categories = "categories";
  static const String hotDeals = "hotDeals";
  static const String others = "others";
  static const String unknown = "unknown";
  static const String aliexpress = "aliexpress";
  static const String specifications = "specifications";
  static const String productDetailsTitle = "productDetailsTitle";
  static const String product = "product";
  static const String platform = "platform";
  static const String colorVariationInstruction = "colorVariationInstruction";
  static const String size = "size";
  static const String quantity = "quantity";
  static const String totalPrice = "totalPrice";
  static const String addToCart = "addToCart";
  static const String updateCart = "updateCart";
  static const String off = "off";
  static const String productInformation = "productInformation";
  static const String packageInformation = "packageInformation";
  static const String weight = "weight";
  static const String dimensions = "dimensions";
  static const String brand = "brand";
  static const String rating = "rating";
  static const String stock = "stock";
  static const String availableStock = "availableStock";
  static const String reviews = "reviews";
  static const String availability = "availability";
  static const String delivery = "delivery";
  static const String prime = "prime";
  static const String description = "description";
  static const String aboutThisProduct = "aboutThisProduct";
  static const String topReviews = "topReviews";
  static const String byAuthor = "byAuthor";
  static const String allColors = "allColors";
  static const String shein = "shein";
  static const String sheinFavoriteTitle = "sheinFavoriteTitle";
  static const String trending = "trending";
  static const String productAddedToCart = "productAddedToCart";
  static const String productUpdatedInCart = "productUpdatedInCart";
  static const String quantityIncreased = "quantityIncreased";
  static const String quantityDecreased = "quantityDecreased";
  static const String searchAgain = "searchAgain";
  static const String searchByImage = "searchByImage";
  static const String tryAgain = "tryAgain";
  static const String textloading = "textloading";
  static const String noMoreData = "noMoreData";
  static const String alibaba = "alibaba";
  static const String bestProducts = "bestProducts";
  static const String doubleTapImageInstruction = "doubleTapImageInstruction";
  static const String unlimited = "unlimited";
  static const String price = "price";
  static const String quantityRange = "quantityRange";
  static const String totalWithQuantity = "totalWithQuantity";
  static const String priceWithAmount = "priceWithAmount";
  static const String sellerInformation = "sellerInformation";
  static const String contactWithName = "contactWithName";
  static const String minQuantityLabel = "minQuantityLabel";
  static const String itemInCartMessage = "itemInCartMessage";
  static const String updateQuantity = "updateQuantity";
  static const String addedToCartLabel = "addedToCartLabel";
  static const String changeOptionsMessage = "changeOptionsMessage";
  static const String relatedItems = "relatedItems";
  static const String color = "color";
  static const String inStock = "inStock";
  static const String mall = "mall";
  static const String attribute = "attribute";
  static const String supportChatTitle = "supportChatTitle";
  static const String serviceOrderTitle = "serviceOrderTitle";
  static const String customerSupportTitle = "customerSupportTitle";
  static const String chatEnded = "chatEnded";
  static const String startConversation = "startConversation";
  static const String noMessagesYet = "noMessagesYet";
  static const String localServicesTitle = "localServicesTitle";
  static const String localServiceOrdersTitle = "localServiceOrdersTitle";
  static const String searchServiceHint = "searchServiceHint";
  static const String chatForService = "chatForService";
  static const String editServiceChat = "editServiceChat";
  static const String serviceAmendment = "serviceAmendment";
  static const String quotedPrice = "quotedPrice";
  static const String unknownService = "unknownService";
  static const String priceApproved = "priceApproved";
  static const String completeOrder = "completeOrder";
  static const String date = "date";
  static const String myLocation = "myLocation";
  static const String addAddressSuccess = "addAddressSuccess";
  static const String addAddressFailed = "addAddressFailed";
  static const String updateAddressSuccess = "updateAddressSuccess";
  static const String updateAddressFailed = "updateAddressFailed";
  static const String reorder = "reorder";
  static const String reordering = "reordering";
  static const String cancelOrder = "cancelOrder";
  static const String cancelling = "cancelling";
  static const String promoCode = "promoCode";
  static const String enterPromoCode = "enterPromoCode";
  static const String deliveryFees = "deliveryFees";
  static const String promocodeDiscount = "promocodeDiscount";
  static const String placeOrder = "placeOrder";
  static const String updateProfile = "updateProfile";
  static const String displayCurrency = "displayCurrency";
  static const String update = "update";
  static const String contactUsHelpTitle = "contactUsHelpTitle";
  static const String contactUsHelpBody = "contactUsHelpBody";
  static const String contactWhatsApp = "contactWhatsApp";
  static const String whatsappError = "whatsappError";
  static const String updateSuccess = "updateSuccess";
  static const String tipsAppreciateTitle = "tipsAppreciateTitle";
  static const String tipsAppreciateBody = "tipsAppreciateBody";
  static const String customTip = "customTip";
  static const String enterAmountEGP = "enterAmountEGP";
  static const String enterAmountUSD = "enterAmountUSD";
  static const String orderNote = "orderNote";
  static const String orderNoteHint = "orderNoteHint";
  static const String paymentNotice = "paymentNotice";
  static const String reviewFeeLabel = "reviewFeeLabel";
  static const String tipsLabel = "tipsLabel";
  static const String reviewService = "reviewService";
  static const String privacyPolicy = "privacyPolicy";
  static const String termsAndConditions = "termsAndConditions";
  static const String legal = "legal";

  // Service Order Details Keys
  static const String serviceAddressTitle = "serviceAddressTitle";
  static const String serviceBuilding = "serviceBuilding";
  static const String serviceFloor = "serviceFloor";
  static const String serviceApartment = "serviceApartment";
  static const String notesTitle = "notesTitle";
  static const String serviceDetailsTitle = "serviceDetailsTitle";
  static const String serviceInfoTitle = "serviceInfoTitle";
  static const String serviceNumber = "serviceNumber";
  static const String serviceDate = "serviceDate";
  static const String serviceStatus = "serviceStatus";
  static const String statusNew = "statusNew";
  static const String statusPriceQuoted = "statusPriceQuoted";
  static const String statusApproved = "statusApproved";
  static const String statusRejected = "statusRejected";
  static const String statusCompleted = "statusCompleted";
  static const String statusCancelled = "statusCancelled";
  static const String statusUnknown = "statusUnknown";

  // Additional Keys - Chat & Support
  static const String imageAttached = "imageAttached";
  static const String pressSendToUploadImage = "pressSendToUploadImage";
  static const String chooseImageSource = "chooseImageSource";
  static const String gallery = "gallery";
  static const String camera = "camera";
  static const String messagesFromSupport = "messagesFromSupport";

  // Additional Keys - Order Status Extended
  static const String pendingAdminReview = "pendingAdminReview";
  static const String adminNotes = "adminNotes";
  static const String adminApproved = "adminApproved";
  static const String awaitingPayment = "awaitingPayment";
  static const String inOrder = "inOrder";
  static const String inTransit = "inTransit";

  // Additional Keys - Local Service
  static const String newService = "newService";
  static const String inChat = "inChat";
  static const String trackService = "trackService";
  static const String serviceRejected = "serviceRejected";
  static const String serviceCancelled = "serviceCancelled";
  static const String requestRejectedByAdmin = "requestRejectedByAdmin";
  static const String serviceCancelledMessage = "serviceCancelledMessage";
  static const String priceSet = "priceSet";

  // Additional Keys - Currency & Settings
  static const String selectDisplayCurrency = "selectDisplayCurrency";
  static const String confirm = "confirm";

  // Additional Keys - Maps & Location
  static const String notes = "notes";
  static const String addSpecialInstructions = "addSpecialInstructions";
  static const String locationLabel = "locationLabel";
  static const String searchPlace = "searchPlace";

  // Additional Keys - Dialog & Alerts
  static const String confirmCancellation = "confirmCancellation";
  static const String confirmCancelOrderMessage = "confirmCancelOrderMessage";
  static const String no = "no";
  static const String yesCancelOrder = "yesCancelOrder";
  static const String orderCancelledSuccess = "orderCancelledSuccess";
  static const String errorCancellingOrder = "errorCancellingOrder";
  static const String cannotCancelOrder = "cannotCancelOrder";
  static const String ok = "ok";
  static const String info = "info";
  static const String noDescriptionAvailable = "noDescriptionAvailable";

  // Additional Keys - Error Messages
  static const String errorWithMessage = "errorWithMessage";
  static const String imageUploadFailed = "imageUploadFailed";
  static const String errorUploadingImage = "errorUploadingImage";

  // Additional Keys - Success Messages
  static const String verificationCodeSent = "verificationCodeSent";
  static const String loginSuccess = "loginSuccess";
  static const String verificationSuccess = "verificationSuccess";

  // Additional Keys - Network
  static const String noInternetConnection = "noInternetConnection";
  static const String internetConnectionRestored = "internetConnectionRestored";

  // Additional Keys - Service Order
  static const String serviceNotFound = "serviceNotFound";
  static const String pleaseSelectAddress = "pleaseSelectAddress";

  // Additional Keys - Favorites
  static const String removedFromFavorites = "removedFromFavorites";

  // Additional Keys - Checkout
  static const String orderPlacedSuccessfully = "orderPlacedSuccessfully";

  // Additional Keys - Service Order Content
  static const String agreedPrice = "agreedPrice";
  static const String confirmAndOrder = "confirmAndOrder";

  // Our Products (Local Products)
  static const String ourProducts = "ourProducts";
  static const String ourProductsFeatured = "ourProductsFeatured";
  static const String ourProductsYouMightLike = "ourProductsYouMightLike";
  static const String searchInOurProducts = "searchInOurProducts";
  static const String viewAll = "viewAll";
  static const String noProductsFound = "noProductsFound";
  static const String saltk = "saltk";
  static const String productDetails = "productDetails";
  static const String addedToCart = "addedToCart";
  static const String relatedProducts = "relatedProducts";
  static const String seeAll = "seeAll";
}
