import 'package:get/get.dart';

class MyTrenslition extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "chooseLang": "اختر اللغة",
      "onboardingTitle1": "طلبك يصل إليك سريعاً",
      "onboardingTitle2": "منتجات العالم بين يديك",
      "onboardingTitle3": "أضف المنتجات بلمسة واحدة",
      "onboardingTitle4": "توصيل سريع",
      "onboardingBody1":
          "نحن نهتم بتوصيل طلباتك بسرعة وأمان إلى باب منزلك.\n استمتع بتجربة تسوق متكاملة من الاختيار حتى الاستلام.",
      "onboardingBody2":
          "استكشف ملايين المنتجات من أكبر الموردين العالميين\n فكرتك التجارية تبدأ من هنا، بفرص لا حصر لها.",
      "onboardingBody3":
          "بأدوات بسيطة وواجهة سهل\n، يمكنك اختيار المنتجات التي تناسب علامتك التجارية وإضافتها إلى متجرك فوراً.",
      "onboardingBody4": "توصيل سريع وموثوق \n إلى باب منزلك",
      "continue": "متابعة",
      "loginTitle": "أهلاً بعودتك",
      "loginBody":
          "سجل الدخول باستخدام بريدك الإلكتروني وكلمة المرور أو استمر باستخدام  جوجول مباشرة",
      "emailHint": "ادخل بريدك الالكتروني",
      "VerifycodesignuplHint": "ادخل الكود",
      "passwordHint": "ادخل كلمة المرور",
      "forgotPassword": "هل نسيت كلمة المرور",
      "login": "تسجيل الدخول",
      "noAccount": "ليس لديك حساب؟ ",
      "Orsigninwith": "او سجل ب جوجل",
      "signUp": "إنشاء حساب",
      "signUpTitle": "إنشاء حساب",
      "signUpBody":
          "أكمل التفاصيل الخاصة بك أو استمر باستخدام وسائل التواصل الاجتماعي",
      "usernameHint": "ادخل اسم المستخدم",
      "phoneHint": "ادخل رقم الهاتف",
      "haveAccount": "هل لديك حساب بالفعل؟ ",
      "forgotPasswordTitle": "فحص البريد الإلكتروني",
      "VerifycodesignupTitle": "فحص البريد الكود المرسل لك",
      "forgotPasswordBody": "الرجاء إدخال البريد الإلكتروني لتلقي رمز التحقق",
      "VerifycodesignupBody": "الرجاء إدخال الرمز لتحقق منه!",
      "check": "تحقق",
      "resetPasswordTitle": "إعادة تعيين كلمة المرور",
      "resetPasswordBody": "الرجاء إدخال كلمة المرور الجديدة",
      "confirmPasswordHint": "اعد كتابة كلمة المرور",
      "save": "حفظ",
      "successResetPasswordTitle": "تم بنجاح",
      "successResetPasswordBody": "تم إعادة تعيين كلمة المرور بنجاح",
      "goToLogin": "اذهب إلى صفحة تسجيل الدخول",
      "successSignUpTitle": "تم بنجاح",
      "successSignUpBody": "تم إنشاء الحساب بنجاح",
      "verifyCodeTitle": "التحقق من الرمز",
      "verifyCodeBody": "الرجاء إدخال الرمز المكون من 5 أرقام المرسل إلى",
    },
    "en": {
      "chooseLang": "Choose Language",
      "onboardingTitle1": "Your Order Arrives Quickly",
      "onboardingTitle2": "The World's Products in Your Hands",
      "onboardingTitle3": "Add Products with a Single Touch",
      "onboardingTitle4": "Fast Delivery",
      "onboardingBody1":
          "We care about delivering your orders quickly and safely to your doorstep.\n Enjoy a complete shopping experience from selection to delivery.",
      "onboardingBody2":
          "Explore millions of products from the biggest global suppliers\n Your business idea starts here, with countless opportunities",
      "onboardingBody3":
          "With simple tools and an easy interface,\n you can choose the products that fit your brand and add them to your store instantly.",
      "onboardingBody4": "Fast and reliable delivery \n to your doorstep",
      "continue": "Continue",
      "loginTitle": "Welcome Back",
      "loginBody":
          "Sign In With Your Email And Password OR Continue With Social Media",
      "emailHint": "Enter Your Email",
      "VerifycodesignuplHint": "Enter Your Code",
      "passwordHint": "Enter Your Password",
      "forgotPassword": "Forgot Password",
      "login": "Login",
      "noAccount": "Don't have an account? ",
      "signUp": "Sign Up",
      "signUpTitle": "Sign Up",
      "signUpBody": "Complete Your Details Or Continue With Social Media",
      "usernameHint": "Enter Your Username",
      "phoneHint": "Enter Your Phone",
      "haveAccount": "Already have an account? ",
      "forgotPasswordTitle": "Check Email",
      "VerifycodesignupTitle": "Check Code",
      "Orsigninwith": "Or sign in with",
      "forgotPasswordBody": "Please Enter Email To Receive A Verification Code",
      "VerifycodesignupBody": "Please Enter Code To Receive A Verification ",
      "check": "Check",
      "resetPasswordTitle": "Reset Password",
      "resetPasswordBody": "Please Enter The New Password",
      "confirmPasswordHint": "Re-enter your password",
      "save": "Save",
      "successResetPasswordTitle": "Success",
      "successResetPasswordBody": "Password has been reset successfully",
      "goToLogin": "Go To Login Page",
      "successSignUpTitle": "Success",
      "successSignUpBody": "Account has been created successfully",
      "verifyCodeTitle": "Verification Code",
      "verifyCodeBody": "Please Enter The 5 Digit Code Sent To",
    },
  };
}
