import 'package:get/get.dart';

class MyTrenslition extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "chooseLang": "اختر اللغة",
      "onboardingTitle1": "مرحبا بك في متجرنا",
      "onboardingTitle2": "استكشف المنتجات",
      "onboardingTitle3": "جاهز للتسوق",
      "onboardingTitle4": "توصيل سريع",
      "onboardingBody1":
          "اكتشف آلاف المنتجات الفريدة من أكبر المتاجر العالمية بأسعار لا تُصدق",

      "onboardingBody2":
          " من الأزياء إلى الإلكترونيات والمستلزمات المنزلية، مجموعات لا حصر لها بانتظارك",
      "onboardingBody3":
          " تسوق بسهولة من AliExpress وAlibaba وShein والمزيد في مكان واحد.",
      "onboardingBody4": "توصيل سريع وموثوق \n إلى باب منزلك",
      "continue": "متابعة",
      "loginTitle": " تسجيل الدخول",
      "loginBody": "يسعدني رؤيتك مرة أخرى!",
      "emailHint": "ادخل بريدك الالكتروني",
      "VerifycodesignuplHint": "ادخل الكود",
      "passwordHint": "ادخل كلمة المرور",
      "forgotPassword": "هل نسيت كلمة المرور",
      "Next": "التالي",
      "noAccount": "ليس لديك حساب؟ ",
      "Orsigninwith": "او سجل ب جوجل",
      "signUp": "إنشاء حساب",
      "signUpTitle": "إنشاء حساب",
      "signUpBody":
          "أكمل التفاصيل الخاصة بك أو استمر باستخدام وسائل التواصل الاجتماعي",
      "usernameHint": "ادخل اسم المستخدم",
      "phoneHint": "ادخل رقم الهاتف",
      "haveAccount": "هل لديك حساب بالفعل؟ ",
      "forgotPasswordTitle": "فحص البريد الإلكتروني",
      "VerifycodesignupTitle": "فحص البريد الكود المرسل لك",
      "forgotPasswordBody": "الرجاء إدخال البريد الإلكتروني لتلقي رمز التحقق",
      "VerifycodesignupBody": "الرجاء إدخال الرمز لتحقق منه!",
      "check": "تحقق",
      "resetPasswordTitle": "إعادة تعيين كلمة المرور",
      "resetPasswordBody": "الرجاء إدخال كلمة المرور الجديدة",
      "confirmPasswordHint": "اعد كتابة كلمة المرور",
      "save": "حفظ",
      "successResetPasswordTitle": "تم بنجاح",
      "successResetPasswordBody": "تم إعادة تعيين كلمة المرور بنجاح",
      "goToLogin": "اذهب إلى صفحة تسجيل الدخول",
      "successSignUpTitle": "تم بنجاح",
      "successSignUpBody": "تم إنشاء الحساب بنجاح",
      "verifyCodeTitle": "التحقق من الرمز",
      "verifyCodeBody": "الرجاء إدخال الرمز المكون من 5 أرقام المرسل إلى",
      "textloading":
          "نقوم الآن بجلب بيانات المنتج. أحيانًا قد يستغرق الأمر بضع ثوانٍ بسبب حجم البيانات وعدد المنتجات — نشكرك على صبرك.",
    },
    "en": {
      "chooseLang": "Choose Language",
      "onboardingTitle1": "Hello, Beautiful!",
      "onboardingTitle2": "Find Your Styles",
      "onboardingTitle3": "Ready to Shop?",
      "onboardingTitle4": "Fast Delivery",
      "onboardingBody1":
          "Discover thousands of unique products from top global stores at unbelievable prices.",
      "onboardingBody2":
          "From fashion to electronics and home essentials, endless collections await you",
      "onboardingBody3":
          "Shop effortlessly from AliExpress, Alibaba, Shein, and more, all in one place.",
      "onboardingBody4": "Fast and reliable delivery \n to your doorstep",
      "continue": "Continue",
      "loginTitle": "Login",
      "loginBody": "Good to see you back!",
      "emailHint": "Enter Your Email",
      "VerifycodesignuplHint": "Enter Your Code",
      "passwordHint": "Enter Your Password",
      "forgotPassword": "Forgot Password",
      "Next": "Next",
      "noAccount": "Don't have an account? ",
      "signUp": "Sign Up",
      "signUpTitle": "Sign Up",
      "signUpBody": "Complete Your Details Or Continue With Social Media",
      "usernameHint": "Enter Your Username",
      "phoneHint": "Enter Your Phone",
      "haveAccount": "Already have an account? ",
      "forgotPasswordTitle": "Check Email",
      "VerifycodesignupTitle": "Check Code",
      "Orsigninwith": "Or sign in with",
      "forgotPasswordBody": "Please Enter Email To Receive A Verification Code",
      "VerifycodesignupBody": "Please Enter Code To Receive A Verification ",
      "check": "Check",
      "resetPasswordTitle": "Reset Password",
      "resetPasswordBody": "Please Enter The New Password",
      "confirmPasswordHint": "Re-enter your password",
      "save": "Save",
      "successResetPasswordTitle": "Success",
      "successResetPasswordBody": "Password has been reset successfully",
      "goToLogin": "Go To Login Page",
      "successSignUpTitle": "Success",
      "successSignUpBody": "Account has been created successfully",
      "verifyCodeTitle": "Verification Code",
      "verifyCodeBody":
          "Enter 5-digits code we sent you\n on your phone number",
      "textloading":
          'We\'re fetching the product details now. This may take a few seconds due to the amount of data and the number of products — thank you for your patience.',
    },
  };
}
