import 'package:e_comerece/core/loacallization/strings_keys.dart';
import 'package:get/get.dart';

class MyTrenslition extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      // Splashscreen
      "appName": "سلتك",
      "letsGetStarted": "لنبدأ",
      "alreadyHaveAccount": "هل لديك حساب بالفعل؟",

      // Exit Dialog
      "exitDialogTitle": "تحذير",
      "exitDialogMessage": "هل تريد الخروج من التطبيق نهائياً؟",
      "cancel": "إلغاء",
      "exit": "خروج",

      // Bottom Nav Bar
      StringsKeys.navHome: "الرئيسية",
      StringsKeys.navCart: "السلة",
      StringsKeys.navOrders: "الطلبات",
      StringsKeys.navServices: "خدمات",
      StringsKeys.navProfile: "حسابي",

      // Platform Names
      StringsKeys.platformShein: "شي إن",
      StringsKeys.platformAlibaba: "علي بابا",
      StringsKeys.platformAliexpress: "علي إكسبريس",
      StringsKeys.platformAmazon: "أمازون",

      "google": "جوجل",
      "gotIt": "فهمت",
      "error": "خطأ",
      "passwordIncorrect": "كلمة المرور غير صحيحة",
      "accountNotFound": "الحساب غير موجود",
      "createAccount": "إنشاء \nحساب",
      "login": "تسجيل الدخول",
      "emailOrPhoneExists": "الايميل او رقم الهاتف موجدين سابقا",
      "resendVerifyCode": "إعادة إرسال رمز التحقق",

      "chooseLang": "اختر اللغة",
      "onboardingTitle1": "مرحبا بك في متجرنا",
      "onboardingTitle2": "استكشف المنتجات",
      "onboardingTitle3": "جاهز للتسوق",
      "onboardingTitle4": "توصيل سريع",
      "onboardingBody1":
          "اكتشف آلاف المنتجات الفريدة من أكبر المتاجر العالمية بأسعار لا تُصدق",

      "onboardingBody2":
          " من الأزياء إلى الإلكترونيات والمستلزمات المنزلية، مجموعات لا حصر لها بانتظارك",
      "onboardingBody3":
          " تسوق بسهولة من AliExpress وAlibaba وShein والمزيد في مكان واحد.",
      "onboardingBody4": "توصيل سريع وموثوق \n إلى باب منزلك",
      "continue": "متابعة",
      "loginTitle": " تسجيل الدخول",
      "loginBody": "يسعدني رؤيتك مرة أخرى!",
      "emailHint": "ادخل بريدك الالكتروني",
      "VerifycodesignuplHint": "ادخل الكود",
      "passwordHint": "ادخل كلمة المرور",
      "forgotPassword": "هل نسيت كلمة المرور",
      "Next": "التالي",
      "noAccount": "ليس لديك حساب؟ ",
      "Orsigninwith": "او سجل ب جوجل",
      "signUp": "إنشاء حساب",
      "signUpTitle": "إنشاء حساب",
      "signUpBody":
          "أكمل التفاصيل الخاصة بك أو استمر باستخدام وسائل التواصل الاجتماعي",
      "usernameHint": "ادخل اسم المستخدم",
      "phoneHint": "ادخل رقم الهاتف",
      "haveAccount": "هل لديك حساب بالفعل؟ ",
      "forgotPasswordTitle": "فحص البريد الإلكتروني",
      "VerifycodesignupTitle": "فحص البريد الكود المرسل لك",
      "forgotPasswordBody": "الرجاء إدخال البريد الإلكتروني لتلقي رمز التحقق",
      "VerifycodesignupBody": "الرجاء إدخال الرمز لتحقق منه!",
      "check": "تحقق",
      "resetPasswordTitle": "إعادة تعيين كلمة المرور",
      "resetPasswordBody": "الرجاء إدخال كلمة المرور الجديدة",
      "confirmPasswordHint": "اعد كتابة كلمة المرور",
      "save": "حفظ",
      "successResetPasswordTitle": "تم بنجاح",
      "successResetPasswordBody": "تم إعادة تعيين كلمة المرور بنجاح",
      "goToLogin": "اذهب إلى صفحة تسجيل الدخول",
      "back": "رجوع",
      "hello": "مرحبا،",
      "notYou": "ليس أنت؟",
      "successSignUpTitle": "تم بنجاح",
      "successSignUpBody": "تم إنشاء الحساب بنجاح",
      "verifyCodeTitle": "التحقق من الرمز",
      "verifyCodeBody": "الرجاء إدخال الرمز المكون من 5 أرقام المرسل إلى",
      "incorrectCode": "الكود غير صحيح",
      "passwordNotMatch": "كلمة المرور غير متطابقة",

      // Verification Method Translations - Arabic
      "chooseVerificationMethod": "اختر طريقة التحقق",
      "verificationMethodBody": "كيف تريد استلام رمز التحقق؟",
      "sendViaSms": "إرسال عبر رسالة SMS",
      "sendViaSmsDesc": "سيتم إرسال الرمز إلى رقم هاتفك",
      "sendViaEmail": "إرسال عبر البريد الإلكتروني",
      "sendViaEmailDesc": "سيتم إرسال الرمز إلى بريدك الإلكتروني",
      "smsSendFailed": "فشل إرسال رسالة SMS",
      "tryAnotherMethod": "يرجى اختيار طريقة أخرى أو المحاولة لاحقاً",
      "trySmsAgain": "حاول مرة أخرى عبر SMS",
      "tryWithEmail": "حاول بالبريد الإلكتروني بدلاً من ذلك",
      "emailOrPhoneHint": "البريد الإلكتروني أو رقم الهاتف",
      "verifyViaEmail": "التحقق عبر البريد الإلكتروني",
      "verifyViaPhone": "التحقق عبر الهاتف (SMS)",
      "codeSentToPhone": "تم إرسال الرمز إلى هاتفك",
      "codeSentToEmail": "تم إرسال الرمز إلى بريدك الإلكتروني",

      "textloading":
          "نقوم الآن بجلب بيانات المنتج. أحيانًا قد يستغرق الأمر بضع ثوانٍ بسبب حجم البيانات وعدد المنتجات — نشكرك على صبرك.",
      "all": "الكل",
      "productFromAliexpress": "منتجات من علي إكسبريس",
      "loadMoreAliexpress": "تحميل المزيد من علي إكسبريس",
      "showLessAliexpress": "عرض أقل من علي إكسبريس",
      "productFromAlibaba": "منتجات من علي بابا",
      "loadMoreAlibaba": "تحميل المزيد من علي بابا",
      "showLessAlibaba": "عرض أقل من علي بابا",
      "productFromAmazon": "منتجات من أمازون",
      "loadMoreAmazon": "تحميل المزيد من أمازون",
      "showLessAmazon": "عرض أقل من أمازون",
      "productFromShein": "منتجات من شي إن",
      "loadMoreShein": "تحميل المزيد من شي إن",
      "showLessShein": "عرض أقل من شي إن",
      "bestFromAliexpress": "الأفضل من علي إكسبريس",
      "bestFromAlibaba": "الأفضل من علي بابا",
      "hotDealsFromAmazon": "عروض ساخنة من أمازون",
      "trendingProductsFromShein": "المنتجات الرائجة من شي إن",
      "sales": "مبيعة",
      "searchHint": "بحث عن منتج",
      "searchPlatforms": "(علي إكسبريس، شي إن،...)",
      "searchForProducts": "ابحث عن منتجاتك المفضلة",
      "cantBeEmpty": "لا يمكن أن يكون فارغاً",
      "notValidUsername": "اسم المستخدم غير صالح",
      "notValidEmail": "البريد الإلكتروني غير صالح",
      "notValidEmailOrPhone": "يرجى إدخال بريد إلكتروني أو رقم هاتف صحيح",
      "cantBeLessThan": "لا يمكن أن يكون أقل من",
      "cantBeLargerThan": "لا يمكن أن يكون أكبر من",
      "disableNotifications": "تعطيل الإشعارات",
      "historyChats": "سجل المحادثات معنا",
      "address": "العناوين",
      "aboutUs": "من نحن",
      "contactUs": "تواصل معنا",
      "logout": "تسجيل الخروج",
      "language": "اللغة",
      "deliveryAddress": "عنوان التوصيل",
      "addAddress": "إضافة عنوان",
      "deleteAddress": "حذف العنوان",
      "deleteAddressConfirmation": "هل أنت متأكد أنك تريد حذف هذا العنوان؟",
      "delete": "حذف",
      "addressTitle": "عنوان العنوان",
      "city": "المدينة",
      "street": "الشارع",
      "floor": "الطابق",
      "buildingNumber": "رقم المبنى",
      "apartment": "الشقة",
      "phone": "الهاتف",
      "addressLabel": "العنوان",
      "yourName": "اسمك",
      "yourMessage": "رسالتك",
      "messages": "الرسائل",
      "favoritesAll": "المفضلة",
      "couponCode": "كود الكوبون",
      "discountCoupon": "كوبون الخصم",
      "apply": "تطبيق",
      "total": "الإجمالي",
      "checkout": "الدفع",
      "howCouponWorks": "كيف يعمل الكوبون؟",
      "couponExplanation":
          "• يوجد 4 منصّات مدعومة في التطبيق: علي إكسبريس، علي بابا، شي إن، أمازون.\n• بعض الكوبونات تكون خاصة بمنصّة محددة.\n• إذا كان الكوبون خاصًا بمنصّة معيّنة، يجب وجود منتج واحد على الأقل من نفس المنصّة داخل السلة.\n• إذا لم يوجد أي منتج من المنصّة المطلوبة، لا يمكن تطبيق الكوبون.\n• الكوبون من نوع ALL يعمل على جميع المنصّات بدون استثناء.",
      "okay": "حسنًا",
      "orders": "الطلبات",
      "orderDetailsTitle": "تفاصيل الطلب",
      "products": "المنتجات",
      "orderStatusPending": "قيد المراجعة",
      "orderStatusActionRequired": "بانتظار العميل",
      "orderStatusProcessing": "قيد التنفيذ",
      "orderStatusShipped": "تم الشحن",
      "orderStatusCompleted": "مكتمل",
      "orderStatusCancelled": "ملغي",
      "reorder": "إعادة الطلب",
      "reordering": "جاري التحميل...",
      "cancelOrder": "إلغاء الطلب",
      "cancelling": "جاري الإلغاء...",
      "chatForService": "محادثة لطلب الخدمة",
      "orderTrackingTitle": "تتبع حالة الطلب",
      "orderStatusCancelledTitle": "الطلب ملغي",
      "orderCancelledBody": "لقد تم إلغاء هذا الطلب",
      "orderPrefix": "طلب",
      "unknownStatus": "غير معروف",
      "notAvailable": "غير متوفر",
      "subtotal": "المجموع الفرعي",
      "discount": "الخصم",
      "shipping": "الشحن",
      "totalAmount": "الإجمالي",
      "orderInformation": "معلومات الطلب",
      "orderIdLabel": "رقم الطلب",
      "orderDateLabel": "تاريخ الطلب",
      "orderStatusLabel": "حالة الطلب",
      "paymentMethodLabel": "طريقة الدفع",
      "paymentStatusLabel": "حالة الدفع",
      "visa": "فيزا",
      "mastercard": "ماستر كارد",
      "cash": "كاش",
      "paid": "مدفوع",
      "pendingPayment": "في انتظار الدفع",
      "failedStatus": "فشل",
      "notDefined": "غير محدد",
      "orderSummary": "ملخص الطلب",
      "changeLanguage": "تغيير اللغة",
      "cart": "عربة التسوق",
      "alert": "تنبيه",
      "maxQuantityReached":
          "لقد وصلت إلى أقصى كمية متاحة لهذا المنتج بكل خياراته",
      "couponEmpty": "الكوبون فارغ",
      "couponAppliedSuccess": "تم تطبيق الكوبون بنجاح",
      "couponUsedOrExpired": "الكوبون مستخدم من قبل او منتهى صلاحيته",
      "couponInvalid": "الكوبون غير صحيح",
      "cartEmpty": "السلة فارغة",
      "couponSpecificPlatformError":
          "الكوبون خاص بمنصة @platform ، ولا يوجد منتجات منها في السلة.",
      "favoritesPlatform": "مفضلة @platform",
      "startPriceRandom": "أقل سعر: غير محدد",
      "startPriceLabel": "أقل سعر: ",
      "endPriceRandom": "أعلى سعر: غير محدد",
      "endPriceLabel": "أعلى سعر: ",
      "priceFilterNote":
          "تنبيه: يتم تصفية الأسعار بالدولار الأمريكي، ولا تتأثر بالعملة المختارة للعرض.",
      "startPrice": "أقل سعر",
      "endPrice": "أعلى سعر",
      "change": "تغيير",
      "amazonTitle": "أمازون",
      "categories": "الأقسام",
      "hotDeals": "عروض ساخنة",
      "others": "أخرى",
      "unknown": "غير معروف",
      "aliexpress": "علي إكسبريس",
      "productDetailsTitle": "تفاصيل المنتج",
      "product": "منتج",
      "platform": "المنصة",
      "colorVariationInstruction": "اللون:",
      "size": "المقاس",
      "quantity": "الكمية",
      "totalPrice": "السعر الإجمالي",
      "addToCart": "أضف إلى السلة",
      "updateCart": "تحديث السلة",
      "off": "خصم",
      "productInformation": "معلومات المنتج",
      "packageInformation": "معلومات الشحنة",
      "weight": "الوزن",
      "dimensions": "الأبعاد",
      "brand": "العلامة التجارية",
      "rating": "التقييم",
      "stock": "المخزون",
      "availableStock": "المخزون المتوفر",
      "reviews": "مراجعة",
      "specifications": "المواصفات",
      "sizeChart": "جدول المقاسات",
      "availability": "التوفر",
      "delivery": "التوصيل",
      "prime": "برايم",
      "description": "الوصف",
      "aboutThisProduct": "حول هذا المنتج",
      "topReviews": "أهم المراجعات",
      "byAuthor": "بواسطة",
      "allColors": "متاح بـ @number لون",
      "shein": "شي إن",
      "trending": "شائع",
      "productAddedToCart": "تم اضافة المنتج الي السله ",
      "productUpdatedInCart": "تم تحديث المنتج في السله ",
      "quantityIncreased": "تم زيادة الكمية",
      "quantityDecreased": "تم تقليل الكميه بمقدار 1 ",
      "searchAgain": "تغيير الصورة ",
      "searchByImage": "البحث بالصورة",
      "tryAgain": "حاول مرة أخرى",
      "noMoreData": "لا يوجد المزيد من البيانات",
      "alibaba": "علي بابا",
      "bestProducts": "أفضل المنتجات",
      "doubleTapImageInstruction": "اضغط مرتين لرؤية الصورة الكاملة",
      "unlimited": "غير محدود",
      "price": "السعر",
      "quantityRange": "لعدد @min - @max",
      "totalWithQuantity": "الإجمالي (@quantity @unit):",
      "priceWithAmount": "السعر @price",
      "sellerInformation": "معلومات البائع",
      "contactWithName": "للتواصل: @name",
      "minQuantityLabel": "الحد الأدنى: @min",
      "itemInCartMessage":
          "هذا المنتج (بالخيارات المختارة) موجود بالفعل في سلتك.",
      "updateQuantity": "تحديث الكمية",
      "addedToCartLabel": "تم الإضافة للسلة",
      "changeOptionsMessage":
          "حاول تغيير المقاس أو اللون أو الموديل لإضافته مرة أخرى.",
      StringsKeys.relatedItems: "منتجات ذات صلة",
      StringsKeys.color: "اللون",
      StringsKeys.inStock: "متوفر",
      StringsKeys.mall: "متجر",
      StringsKeys.attribute: "السمة",
      StringsKeys.supportChatTitle: "محادثات الدعم",
      StringsKeys.serviceOrderTitle: "طلب خدمة",
      StringsKeys.customerSupportTitle: "دعم العملاء",
      StringsKeys.chatEnded: "تم إنهاء المحادثة",
      StringsKeys.startConversation: "ابدأ المحادثة الآن",
      StringsKeys.noMessagesYet: "لا توجد رسائل بعد",
      StringsKeys.localServicesTitle: "الخدمات المحلية",
      StringsKeys.searchServiceHint: "بحث عن خدمة",
      StringsKeys.localServiceOrdersTitle: "طلبات الخدمات المحلية",
      StringsKeys.editServiceChat: "تعديل الخدمة (محادثة)",
      StringsKeys.serviceAmendment: "تعديل الخدمة",
      StringsKeys.quotedPrice: "السعر المحدد",
      StringsKeys.unknownService: "خدمة غير معروفة",
      StringsKeys.priceApproved: "السعر الذي تم تحديده: @price",
      StringsKeys.completeOrder: "إتمام الطلب",
      StringsKeys.date: "التاريخ",
      StringsKeys.myLocation: "موقعي",
      StringsKeys.addAddressSuccess: "تم إضافة العنوان بنجاح",
      StringsKeys.addAddressFailed: "فشل إضافة العنوان",
      StringsKeys.updateAddressSuccess: "تم تعديل العنوان بنجاح",
      StringsKeys.updateAddressFailed: "فشل تعديل العنوان",
      StringsKeys.promoCode: "الرمز الترويجي",
      StringsKeys.enterPromoCode: "أدخل الرمز الترويجي",
      StringsKeys.deliveryFees: "رسوم التوصيل",
      StringsKeys.promocodeDiscount: "خصم الرمز الترويجي",
      StringsKeys.placeOrder: "إتمام الطلب",
      StringsKeys.updateProfile: "تحديث الملف الشخصي",
      StringsKeys.displayCurrency: "عملة العرض",
      StringsKeys.update: "تحديث",
      StringsKeys.contactUsHelpTitle: "نحن هنا لمساعدتكم",
      StringsKeys.contactUsHelpBody:
          "يسعدنا تواصلكم معنا مباشرة عبر الواتساب للإجابة على جميع استفساراتكم",
      StringsKeys.contactWhatsApp: "تواصل عبر الواتساب",
      StringsKeys.whatsappError: "عذراً، لم نتمكن من فتح تطبيق الواتساب",
      StringsKeys.updateSuccess: "تم التحديث بنجاح",
      StringsKeys.tipsAppreciateTitle: "تقدير خدمة التوصيل بمكافأة",
      StringsKeys.tipsAppreciateBody:
          "المبلغ بالكامل يذهب مباشرة إلى بطل التوصيل",
      StringsKeys.customTip: "مخصص",
      StringsKeys.enterAmountEGP: "أدخل المبلغ (جنيه مصري)",
      StringsKeys.enterAmountUSD: "أدخل المبلغ (بالدولار)",
      StringsKeys.orderNote: "ملاحظة",
      StringsKeys.orderNoteHint: "اكتب ملاحظتك هنا...",
      StringsKeys.paymentNotice:
          "سيتم الدفع بعد تأكيد الإدارة للطلب والمنتجات والأسعار. سيصلكم إشعار بذلك، وفي حال وجود أي استفسار سيتم التواصل معكم عبر الدردشة الخاصة بالطلب أو رسالة من الإدارة.",
      StringsKeys.reviewFeeLabel: "رسوم المراجعة",
      StringsKeys.tipsLabel: "المكافأة",
      StringsKeys.reviewService: "خدمة المراجعة",
      StringsKeys.privacyPolicy: "سياسة الخصوصية",
      StringsKeys.termsAndConditions: "الشروط والأحكام",
      StringsKeys.legal: "المعلومات القانونية",

      // Service Order Details
      StringsKeys.serviceAddressTitle: "عنوان الخدمة",
      StringsKeys.serviceBuilding: "المبنى",
      StringsKeys.serviceFloor: "الطابق",
      StringsKeys.serviceApartment: "الشقة",
      StringsKeys.notesTitle: "ملاحظات",
      StringsKeys.serviceDetailsTitle: "تفاصيل الخدمة",
      StringsKeys.serviceInfoTitle: "معلومات الخدمة",
      StringsKeys.serviceNumber: "رقم الخدمة",
      StringsKeys.serviceDate: "تاريخ الخدمة",
      StringsKeys.serviceStatus: "حالة الخدمة",
      StringsKeys.statusNew: "جديد",
      StringsKeys.statusPriceQuoted: "تم تحديد السعر",
      StringsKeys.statusApproved: "تمت الموافقة",
      StringsKeys.statusRejected: "مرفوض",
      StringsKeys.statusCompleted: "مكتمل",
      StringsKeys.statusCancelled: "ملغي",
      StringsKeys.statusUnknown: "غير معروف",

      // Additional Keys - Chat & Support
      StringsKeys.imageAttached: "صورة مرفقة",
      StringsKeys.pressSendToUploadImage: "اضغط ارسال لإرسال الصورة",
      StringsKeys.chooseImageSource: "اختر مصدر الصورة",
      StringsKeys.gallery: "المعرض",
      StringsKeys.camera: "الكاميرا",
      StringsKeys.messagesFromSupport: "هناك رسائل من الدعم",

      // Additional Keys - Order Status Extended
      StringsKeys.pendingAdminReview: "انتظار مراجعة الأدمن",
      StringsKeys.adminNotes: "ملاحظات من الأدمن",
      StringsKeys.adminApproved: "موافقة الأدمن",
      StringsKeys.awaitingPayment: "انتظار الدفع",
      StringsKeys.inOrder: "في الطلب",
      StringsKeys.inTransit: "في الطريق",

      // Additional Keys - Local Service
      StringsKeys.newService: "خدمة جديدة",
      StringsKeys.inChat: "في المحادثة",
      StringsKeys.trackService: "تتبع الخدمة",
      StringsKeys.serviceRejected: "خدمة مرفوضة",
      StringsKeys.serviceCancelled: "خدمة ملغية",
      StringsKeys.requestRejectedByAdmin: "تم رفض طلبك من قبل الإدارة",
      StringsKeys.serviceCancelledMessage: "تم إلغاء هذه الخدمة",
      StringsKeys.priceSet: "تم تحديد السعر",

      // Additional Keys - Currency & Settings
      StringsKeys.selectDisplayCurrency: "اختر عملة العرض",
      StringsKeys.confirm: "تأكيد",

      // Additional Keys - Maps & Location
      StringsKeys.notes: "ملاحظات",
      StringsKeys.addSpecialInstructions: "أضف أي تعليمات خاصة...",
      StringsKeys.locationLabel: "الموقع",
      StringsKeys.searchPlace: "ابحث عن مكان",

      // Additional Keys - Dialog & Alerts
      StringsKeys.confirmCancellation: "تأكيد الإلغاء",
      StringsKeys.confirmCancelOrderMessage: "هل أنت متأكد من إلغاء هذا الطلب؟",
      StringsKeys.no: "لا",
      StringsKeys.yesCancelOrder: "نعم، إلغاء الطلب",
      StringsKeys.orderCancelledSuccess: "تم إلغاء الطلب بنجاح",
      StringsKeys.errorCancellingOrder: "حدث خطأ أثناء إلغاء الطلب",
      StringsKeys.cannotCancelOrder:
          "لا يمكن إلغاء هذا الطلب. يمكن إلغاء الطلبات في حالة المراجعة أو بانتظار العميل فقط",
      StringsKeys.ok: "حسناً",
      StringsKeys.info: "معلومات",
      StringsKeys.noDescriptionAvailable: "لا يوجد وصف متاح",

      // Additional Keys - Error Messages
      StringsKeys.errorWithMessage: "خطأ",
      StringsKeys.imageUploadFailed: "فشل رفع الصورة، حاول مرة أخرى",
      StringsKeys.errorUploadingImage: "حدث خطأ أثناء رفع الصورة",

      // Additional Keys - Success Messages
      StringsKeys.verificationCodeSent: "تم إرسال رمز التحقق",
      StringsKeys.loginSuccess: "تم تسجيل الدخول بنجاح",
      StringsKeys.verificationSuccess: "تم التحقق بنجاح",

      // Additional Keys - Network
      StringsKeys.noInternetConnection: "الإنترنت غير متوفر الآن",
      StringsKeys.internetConnectionRestored: "تم استعادة الاتصال بالإنترنت",

      // Additional Keys - Service Order
      StringsKeys.serviceNotFound: "الخدمة غير موجودة",
      StringsKeys.pleaseSelectAddress: "يرجى اختيار عنوان",

      // Additional Keys - Favorites
      StringsKeys.removedFromFavorites: "تمت الإزالة من المفضلة",

      // Additional Keys - Checkout
      StringsKeys.orderPlacedSuccessfully: "تم تأكيد الطلب بنجاح",

      // Additional Keys - Service Order Content
      StringsKeys.agreedPrice: "السعر المتفق عليه",
      StringsKeys.confirmAndOrder: "تأكيد وطلب",

      // Our Products (Local Products)
      StringsKeys.ourProducts: "منتجاتنا",
      StringsKeys.ourProductsFeatured: "منتجاتنا المميزة",
      StringsKeys.ourProductsYouMightLike: "منتجاتنا قد تعجبك",
      StringsKeys.searchInOurProducts: "البحث في منتجاتنا",
      StringsKeys.viewAll: "عرض الكل",
      StringsKeys.noProductsFound: "لا توجد منتجات",
      StringsKeys.saltk: "سلتك",
      StringsKeys.productDetails: "تفاصيل المنتج",
      StringsKeys.addedToCart: "تمت الإضافة للسلة",
      StringsKeys.relatedProducts: "منتجات مشابهة",

      // Wallet
      StringsKeys.walletBalance: "رصيد المحفظة",
      StringsKeys.walletTransactions: "معاملات المحفظة",
      StringsKeys.walletNoTransactions: "لا توجد معاملات",
      StringsKeys.walletRecharge: "شحن المحفظة",
      StringsKeys.walletRechargeAmount: "مبلغ الشحن",
      StringsKeys.walletRechargeHint: "أدخل المبلغ المراد شحنه",
      StringsKeys.walletRechargeButton: "شحن الآن",
      StringsKeys.walletRechargeSuccess: "تم شحن المحفظة بنجاح",
      StringsKeys.walletRechargeFailed: "فشل شحن المحفظة",

      // Shein Favorites
      StringsKeys.sheinFavoriteTitle: "مفضلة شي إن",

      // Additional Missing Keys
      StringsKeys.pageNotFound: "الصفحة غير موجودة",
      StringsKeys.aboutService: "عن الخدمة",
      StringsKeys.more: "المزيد",
      StringsKeys.allColorsCount: "جميع الـ @number ألوان",
      StringsKeys.country: "الدولة",
      StringsKeys.invalidPhoneNumber:
          "رقم الهاتف غير صحيح، يرجى التأكد من الرقم",
      StringsKeys.tooManyRequests: "تم إرسال طلبات كثيرة، يرجى المحاولة لاحقاً",
      StringsKeys.quotaExceeded: "تم تجاوز الحد المسموح، يرجى المحاولة لاحقاً",
      StringsKeys.verificationFailed:
          "حدث خطأ في التحقق، يرجى المحاولة مرة أخرى",
      StringsKeys.sessionExpired: "انتهت صلاحية الجلسة، يرجى المحاولة مرة أخرى",
      StringsKeys.invalidVerificationCode: "رمز التحقق غير صحيح",
      StringsKeys.invalidVerificationId:
          "انتهت صلاحية الرمز، يرجى طلب رمز جديد",
      StringsKeys.otpSendFailedUseEmail:
          "فشل إرسال رمز التحقق، يرجى المحاولة عبر البريد الإلكتروني",
      StringsKeys.otpTimeout: "انتهت مهلة الانتظار، يرجى المحاولة مرة أخرى",
      StringsKeys.autoVerificationDone: "تم التحقق تلقائياً",
      StringsKeys.unexpectedErrorTryAgain:
          "حدث خطأ غير متوقع، يرجى المحاولة مرة أخرى",
    },
    "en": {
      // Splashscreen
      "appName": "Slatk",
      "letsGetStarted": "Let's Get Started",
      "alreadyHaveAccount": "Already have an account?",

      // Exit Dialog
      "exitDialogTitle": "Warning",
      "exitDialogMessage": "Do you want to exit the application permanently?",
      "cancel": "Cancel",
      "exit": "Exit",

      // Bottom Nav Bar
      StringsKeys.navHome: "Home",
      StringsKeys.navCart: "Cart",
      StringsKeys.navOrders: "Orders",
      StringsKeys.navServices: "Services",
      StringsKeys.navProfile: "Profile",

      // Platform Names
      StringsKeys.platformShein: "Shein",
      StringsKeys.platformAlibaba: "Alibaba",
      StringsKeys.platformAliexpress: "AliExpress",
      StringsKeys.platformAmazon: "Amazon",

      "google": "Google",
      "gotIt": "Got It",
      "error": "Error",
      "passwordIncorrect": "Password Incorrect",
      "accountNotFound": "Account not found",
      "createAccount": "Create \nAccount",
      "login": "Login",
      "emailOrPhoneExists": "Email or Phone already exists",
      "resendVerifyCode": "Resend Verify Code",

      "chooseLang": "Choose Language",
      "onboardingTitle1": "Hello, Beautiful!",
      "onboardingTitle2": "Find Your Styles",
      "onboardingTitle3": "Ready to Shop?",
      "onboardingTitle4": "Fast Delivery",
      "onboardingBody1":
          "Discover thousands of unique products from top global stores at unbelievable prices.",
      "onboardingBody2":
          "From fashion to electronics and home essentials, endless collections await you",
      "onboardingBody3":
          "Shop effortlessly from AliExpress, Alibaba, Shein, and more, all in one place.",
      "onboardingBody4": "Fast and reliable delivery \n to your doorstep",
      "continue": "Continue",
      "loginTitle": "Login",
      "loginBody": "Good to see you back!",
      "emailHint": "Enter Your Email",
      "VerifycodesignuplHint": "Enter Your Code",
      "passwordHint": "Enter Your Password",
      "forgotPassword": "Forgot Password",
      "Next": "Next",
      "noAccount": "Don't have an account? ",
      "signUp": "Sign Up",
      "signUpTitle": "Sign Up",
      "signUpBody": "Complete Your Details Or Continue With Social Media",
      "usernameHint": "Enter Your Username",
      "phoneHint": "Enter Your Phone",
      "haveAccount": "Already have an account? ",
      "forgotPasswordTitle": "Check Email",
      "VerifycodesignupTitle": "Check Code",
      "Orsigninwith": "Or sign in with",
      "forgotPasswordBody": "Please Enter Email To Receive A Verification Code",
      "VerifycodesignupBody": "Please Enter Code To Receive A Verification ",
      "check": "Check",
      "resetPasswordTitle": "Reset Password",
      "resetPasswordBody": "Please Enter The New Password",
      "confirmPasswordHint": "Re-enter your password",
      "save": "Save",
      "successResetPasswordTitle": "Success",
      "successResetPasswordBody": "Password has been reset successfully",
      "goToLogin": "Go To Login Page",
      "back": "Back",
      "hello": "Hello,",
      "notYou": "Not you?",
      "successSignUpTitle": "Success",
      "successSignUpBody": "Account has been created successfully",
      "verifyCodeTitle": "Verification Code",
      "verifyCodeBody":
          "Enter 5-digits code we sent you\n on your phone number",
      "incorrectCode": "Incorrect code",
      "passwordNotMatch": "Passwords do not match",

      // Verification Method Translations - English
      "chooseVerificationMethod": "Choose Verification Method",
      "verificationMethodBody":
          "How would you like to receive the verification code?",
      "sendViaSms": "Send via SMS",
      "sendViaSmsDesc": "Code will be sent to your phone number",
      "sendViaEmail": "Send via Email",
      "sendViaEmailDesc": "Code will be sent to your email address",
      "smsSendFailed": "Failed to send SMS",
      "tryAnotherMethod": "Please choose another method or try again later",
      "trySmsAgain": "Try SMS again",
      "tryWithEmail": "Try with email instead",
      "emailOrPhoneHint": "Email or Phone Number",
      "verifyViaEmail": "Verify via Email",
      "verifyViaPhone": "Verify via Phone (SMS)",
      "codeSentToPhone": "Code sent to your phone",
      "codeSentToEmail": "Code sent to your email",

      "textloading":
          'We\'re fetching the product details now. This may take a few seconds due to the amount of data and the number of products — thank you for your patience.',
      "all": "All",
      "productFromAliexpress": "Product from Aliexpress",
      "loadMoreAliexpress": "Load more Aliexpress",
      "showLessAliexpress": "Show less Aliexpress",
      "productFromAlibaba": "Product from Alibaba",
      "loadMoreAlibaba": "Load more Alibaba",
      "showLessAlibaba": "Show less Alibaba",
      "productFromAmazon": "Product from Amazon",
      "loadMoreAmazon": "Load more Amazon",
      "showLessAmazon": "Show less Amazon",
      "productFromShein": "Product from Shein",
      "loadMoreShein": "Load more Shein",
      "showLessShein": "Show less Shein",
      "bestFromAliexpress": "Best from AliExpress",
      "bestFromAlibaba": "Best from Alibaba",
      "hotDealsFromAmazon": "Hot Deals from Amazon",
      "trendingProductsFromShein": "Trending Products from Shein",
      "sales": "sales",
      "searchHint": "Search",
      "searchPlatforms": "(AliExpress, Shein,...)",
      "searchForProducts": "Search for your favorite products",
      "cantBeEmpty": "can't be Empty",
      "notValidUsername": "Not Valid Username",
      "notValidEmail": "Not Valid Email",
      "notValidEmailOrPhone": "Please enter a valid email or phone number",
      "cantBeLessThan": "can't be less than",
      "cantBeLargerThan": "can't be larger than",
      "disableNotifications": "Disable Notifications",
      "historyChats": "History Chats with us",
      "address": "Address",
      "aboutUs": "About us",
      "contactUs": "Contact us",
      "logout": "Logout",
      "language": "Language",
      "deliveryAddress": "Delivery Address",
      "addAddress": "Add Address",
      "deleteAddress": "Delete Address",
      "deleteAddressConfirmation":
          "Are you sure you want to delete this address?",
      "delete": "Delete",
      "addressTitle": "Address Title",
      "city": "City",
      "street": "Street",
      "floor": "Floor",
      "buildingNumber": "Building Number",
      "apartment": "Apartment",
      "phone": "Phone",
      "addressLabel": "Address",
      "yourName": "Your Name",
      "yourMessage": "Your Message",
      "messages": "Messages",
      "favoritesAll": "Favorites All",
      "couponCode": "Coupon Code",
      "discountCoupon": "Discount Coupon",
      "apply": "Apply",
      "total": "Total",
      "checkout": "Checkout",
      "howCouponWorks": "How Coupon Works?",
      "couponExplanation":
          "• There are 4 supported platforms in the app: AliExpress, Alibaba, Shein, Amazon.\n• Some coupons are specific to a specific platform.\n• If the coupon is for a specific platform, there must be at least one product from the same platform in the cart.\n• If there are no products from the required platform, the coupon cannot be applied.\n• The ALL type coupon works on all platforms without exception.",
      "okay": "Okay",
      "orders": "Orders",
      "orderDetailsTitle": "Order Details",
      "products": "Products",
      "orderStatusPending": "Pending",
      "orderStatusActionRequired": "Action Required",
      "orderStatusProcessing": "Processing",
      "orderStatusShipped": "Shipped",
      "orderStatusCompleted": "Completed",
      "orderStatusCancelled": "Cancelled",
      "reorder": "Reorder",
      "reordering": "Processing...",
      "cancelOrder": "Cancel Order",
      "cancelling": "Cancelling...",
      "chatForService": "Chat for Service",
      "orderTrackingTitle": "Order Tracking",
      "orderStatusCancelledTitle": "Order Cancelled",
      "orderCancelledBody": "This order has been cancelled",
      "orderPrefix": "Order",
      "unknownStatus": "Unknown",
      "notAvailable": "Not Available",
      "subtotal": "Subtotal",
      "discount": "Discount",
      "shipping": "Shipping",
      "totalAmount": "Total",
      "orderInformation": "Order Information",
      "orderIdLabel": "Order ID",
      "orderDateLabel": "Order Date",
      "orderStatusLabel": "Order Status",
      "paymentMethodLabel": "Payment Method",
      "paymentStatusLabel": "Payment Status",
      "visa": "Visa",
      "mastercard": "Mastercard",
      "cash": "Cash",
      "paid": "Paid",
      "pendingPayment": "Pending Payment",
      "failedStatus": "Failed",
      "notDefined": "Not Defined",
      "orderSummary": "Order Summary",
      "changeLanguage": "Change Language",
      "cart": "Cart",
      "alert": "Alert",
      "maxQuantityReached":
          "You have reached the maximum available quantity for this product with all its options",
      "couponEmpty": "Coupon is empty",
      "couponAppliedSuccess": "Coupon applied successfully",
      "couponUsedOrExpired": "Coupon used before or expired",
      "couponInvalid": "Invalid coupon",
      "cartEmpty": "Cart is empty",
      "couponSpecificPlatformError":
          "The coupon is specific to platform @platform, and there are no products from it in the cart.",
      "favoritesPlatform": "Favorites @platform",
      "startPriceRandom": "Min Price: Any",
      "startPriceLabel": "Min Price: ",
      "endPriceRandom": "Max Price: Any",
      "endPriceLabel": "Max Price: ",
      "priceFilterNote":
          "Note: Price filtering is based on USD and is independent of your display currency.",
      "startPrice": "Min Price",
      "endPrice": "Max Price",
      "change": "Change",
      "amazonTitle": "Amazon",
      "categories": "Categories",
      "hotDeals": "Hot Deals",
      "others": "Others",
      "unknown": "Unknown",
      "aliexpress": "AliExpress",
      "productDetailsTitle": "Product Details",
      "product": "Product",
      "platform": "Platform",
      "colorVariationInstruction": "Color:",
      "size": "Size",
      "quantity": "Quantity",
      "totalPrice": "Total Price",
      "addToCart": "Add to Cart",
      "updateCart": "Update Cart",
      "off": "OFF",
      "productInformation": "Product Information",
      "packageInformation": "Package Information",
      "weight": "Weight",
      "dimensions": "Dimensions",
      "brand": "Brand",
      "rating": "Rating",
      "stock": "Stock",
      "availableStock": "Available Stock",
      "reviews": "reviews",
      "specifications": "Specifications",
      "sizeChart": "Size Chart",
      "availability": "Availability",
      "delivery": "Delivery",
      "prime": "PRIME",
      "description": "Description",
      "aboutThisProduct": "About this product",
      "topReviews": "Top Reviews",
      "byAuthor": "By",
      "allColors": "Available in @number colors",
      "shein": "SHEIN",
      "trending": "Trending",
      "productAddedToCart": "Product added to cart",
      "productUpdatedInCart": "Product updated in cart",
      "quantityIncreased": "Quantity increased",
      "quantityDecreased": "Quantity decreased by 1",
      "searchAgain": "Change Image",
      "searchByImage": "Search By Image",
      "tryAgain": "Try Again",
      "noMoreData": "No more data",
      "alibaba": "Alibaba",
      "bestProducts": "Best Products",
      "doubleTapImageInstruction": "Double tap to see full image",
      "unlimited": "Unlimited",
      "price": "Price",
      "quantityRange": "For @min - @max",
      "totalWithQuantity": "Total (@quantity @unit):",
      "priceWithAmount": "Price @price",
      "sellerInformation": "Seller Information",
      "contactWithName": "Contact: @name",
      "minQuantityLabel": "Min: @min",
      "itemInCartMessage":
          "This item (with the chosen options) is already in your cart.",
      "updateQuantity": "Update Quantity",
      "addedToCartLabel": "Added to Cart",
      "changeOptionsMessage":
          "Try changing size, color, or model to add it again.",
      StringsKeys.relatedItems: "Related Items",
      StringsKeys.color: "Color",
      StringsKeys.inStock: "in stock",
      StringsKeys.mall: "Mall",
      StringsKeys.attribute: "Attribute",
      StringsKeys.supportChatTitle: "Support Chat",
      StringsKeys.serviceOrderTitle: "Service Order",
      StringsKeys.customerSupportTitle: "Customer Support",
      StringsKeys.chatEnded: "Chat has ended",
      StringsKeys.startConversation: "Start a conversation",
      StringsKeys.noMessagesYet: "No messages yet",
      StringsKeys.localServicesTitle: "Local Services",
      StringsKeys.searchServiceHint: "Search for a service",
      StringsKeys.localServiceOrdersTitle: "Local Service Orders",
      StringsKeys.editServiceChat: "Edit Service (Chat)",
      StringsKeys.serviceAmendment: "Service Amendment",
      StringsKeys.quotedPrice: "Quoted Price",
      StringsKeys.unknownService: "Unknown Service",
      StringsKeys.priceApproved: "Quoted Price: @price",
      StringsKeys.completeOrder: "Complete Order",
      StringsKeys.date: "Date",
      StringsKeys.myLocation: "My Location",
      StringsKeys.addAddressSuccess: "Address added successfully",
      StringsKeys.addAddressFailed: "Failed to add address",
      StringsKeys.updateAddressSuccess: "Address updated successfully",
      StringsKeys.updateAddressFailed: "Failed to update address",
      StringsKeys.promoCode: "Promo Code",
      StringsKeys.enterPromoCode: "Enter Promo Code",
      StringsKeys.deliveryFees: "Delivery Fees",
      StringsKeys.promocodeDiscount: "Promocode Discount",
      StringsKeys.placeOrder: "Place Order",
      StringsKeys.updateProfile: "Update Profile",
      StringsKeys.displayCurrency: "Display Currency",
      StringsKeys.update: "Update",
      StringsKeys.contactUsHelpTitle: "We're here to help",
      StringsKeys.contactUsHelpBody:
          "Feel free to contact us directly via WhatsApp for any inquiries",
      StringsKeys.contactWhatsApp: "Contact via WhatsApp",
      StringsKeys.whatsappError: "Could not launch WhatsApp",
      StringsKeys.updateSuccess: "Updated successfully",
      StringsKeys.tipsAppreciateTitle: "Appreciate delivery with tips",
      StringsKeys.tipsAppreciateBody:
          "The whole amount will go directly to the delivery hero",
      StringsKeys.customTip: "Custom",
      StringsKeys.enterAmountEGP: "Enter amount (EGP)",
      StringsKeys.enterAmountUSD: "Enter amount (\$)",
      StringsKeys.orderNote: "Order Note",
      StringsKeys.orderNoteHint: "Write your note here...",
      StringsKeys.paymentNotice:
          "Payment will be made after the administration confirms the order, products, and prices. You will receive a notification, and if there are any inquiries, we will contact you via the order chat or a message from the administration.",
      StringsKeys.reviewFeeLabel: "Review Fee",
      StringsKeys.tipsLabel: "Tips",
      StringsKeys.reviewService: "Review Service",
      StringsKeys.privacyPolicy: "Privacy Policy",
      StringsKeys.termsAndConditions: "Terms & Conditions",
      StringsKeys.legal: "Legal Information",

      // Service Order Details
      StringsKeys.serviceAddressTitle: "Service Address",
      StringsKeys.serviceBuilding: "Building",
      StringsKeys.serviceFloor: "Floor",
      StringsKeys.serviceApartment: "Apartment",
      StringsKeys.notesTitle: "Notes",
      StringsKeys.serviceDetailsTitle: "Service Details",
      StringsKeys.serviceInfoTitle: "Service Information",
      StringsKeys.serviceNumber: "Service Number",
      StringsKeys.serviceDate: "Service Date",
      StringsKeys.serviceStatus: "Service Status",
      StringsKeys.statusNew: "New",
      StringsKeys.statusPriceQuoted: "Price Quoted",
      StringsKeys.statusApproved: "Approved",
      StringsKeys.statusRejected: "Rejected",
      StringsKeys.statusCompleted: "Completed",
      StringsKeys.statusCancelled: "Cancelled",
      StringsKeys.statusUnknown: "Unknown",

      // Additional Keys - Chat & Support
      StringsKeys.imageAttached: "Image Attached",
      StringsKeys.pressSendToUploadImage: "Press send to upload the image",
      StringsKeys.chooseImageSource: "Choose Image Source",
      StringsKeys.gallery: "Gallery",
      StringsKeys.camera: "Camera",
      StringsKeys.messagesFromSupport: "You have messages from support",

      // Additional Keys - Order Status Extended
      StringsKeys.pendingAdminReview: "Pending Admin Review",
      StringsKeys.adminNotes: "Admin Notes",
      StringsKeys.adminApproved: "Admin Approved",
      StringsKeys.awaitingPayment: "Awaiting Payment",
      StringsKeys.inOrder: "In Order",
      StringsKeys.inTransit: "In Transit",

      // Additional Keys - Local Service
      StringsKeys.newService: "New Service",
      StringsKeys.inChat: "In Chat",
      StringsKeys.trackService: "Track Service",
      StringsKeys.serviceRejected: "Service Rejected",
      StringsKeys.serviceCancelled: "Service Cancelled",
      StringsKeys.requestRejectedByAdmin: "Your request was rejected by admin",
      StringsKeys.serviceCancelledMessage: "This service has been cancelled",
      StringsKeys.priceSet: "Price Set",

      // Additional Keys - Currency & Settings
      StringsKeys.selectDisplayCurrency: "Select Display Currency",
      StringsKeys.confirm: "Confirm",

      // Additional Keys - Maps & Location
      StringsKeys.notes: "Notes",
      StringsKeys.addSpecialInstructions: "Add any special instructions...",
      StringsKeys.locationLabel: "Location",
      StringsKeys.searchPlace: "Search Place",

      // Additional Keys - Dialog & Alerts
      StringsKeys.confirmCancellation: "Confirm Cancellation",
      StringsKeys.confirmCancelOrderMessage:
          "Are you sure you want to cancel this order?",
      StringsKeys.no: "No",
      StringsKeys.yesCancelOrder: "Yes, Cancel Order",
      StringsKeys.orderCancelledSuccess: "Order cancelled successfully",
      StringsKeys.errorCancellingOrder: "Error cancelling order",
      StringsKeys.cannotCancelOrder:
          "Cannot cancel this order. Only orders in pending or action required status can be cancelled",
      StringsKeys.ok: "OK",
      StringsKeys.info: "Info",
      StringsKeys.noDescriptionAvailable: "No description available",

      // Additional Keys - Error Messages
      StringsKeys.errorWithMessage: "Error",
      StringsKeys.imageUploadFailed: "Image upload failed, please try again",
      StringsKeys.errorUploadingImage: "Error uploading image",

      // Additional Keys - Success Messages
      StringsKeys.verificationCodeSent: "Verification code sent",
      StringsKeys.loginSuccess: "Login successful",
      StringsKeys.verificationSuccess: "Verification successful",

      // Additional Keys - Network
      StringsKeys.noInternetConnection: "No internet connection",
      StringsKeys.internetConnectionRestored: "Internet connection restored",

      // Additional Keys - Service Order
      StringsKeys.serviceNotFound: "Service not found",
      StringsKeys.pleaseSelectAddress: "Please select an address",

      // Additional Keys - Favorites
      StringsKeys.removedFromFavorites: "Removed from favorites",

      // Additional Keys - Checkout
      StringsKeys.orderPlacedSuccessfully: "Order placed successfully",

      // Additional Keys - Service Order Content
      StringsKeys.agreedPrice: "Agreed Price",
      StringsKeys.confirmAndOrder: "Confirm & Order",

      // Our Products (Local Products)
      StringsKeys.ourProducts: "Our Products",
      StringsKeys.ourProductsFeatured: "Featured Products",
      StringsKeys.ourProductsYouMightLike: "Our products you might like",
      StringsKeys.searchInOurProducts: "Search in our products",
      StringsKeys.viewAll: "View All",
      StringsKeys.noProductsFound: "No products found",
      StringsKeys.saltk: "SaltK",
      StringsKeys.productDetails: "Product Details",
      StringsKeys.addedToCart: "Added to cart",
      StringsKeys.relatedProducts: "Related Products",

      // Wallet
      StringsKeys.walletBalance: "Wallet Balance",
      StringsKeys.walletTransactions: "Wallet Transactions",
      StringsKeys.walletNoTransactions: "No transactions",
      StringsKeys.walletRecharge: "Recharge Wallet",
      StringsKeys.walletRechargeAmount: "Recharge Amount",
      StringsKeys.walletRechargeHint: "Enter the amount to recharge",
      StringsKeys.walletRechargeButton: "Recharge Now",
      StringsKeys.walletRechargeSuccess: "Wallet recharged successfully",
      StringsKeys.walletRechargeFailed: "Wallet recharge failed",

      // Shein Favorites
      StringsKeys.sheinFavoriteTitle: "Shein Favorites",

      // Additional Missing Keys
      StringsKeys.pageNotFound: "Page Not Found",
      StringsKeys.aboutService: "About Service",
      StringsKeys.more: "More",
      StringsKeys.allColorsCount: "all @number colors",
      StringsKeys.country: "Country",
      StringsKeys.invalidPhoneNumber:
          "Invalid phone number, please check the number",
      StringsKeys.tooManyRequests: "Too many requests, please try again later",
      StringsKeys.quotaExceeded: "Quota exceeded, please try again later",
      StringsKeys.verificationFailed: "Verification failed, please try again",
      StringsKeys.sessionExpired: "Session expired, please try again",
      StringsKeys.invalidVerificationCode: "Invalid verification code",
      StringsKeys.invalidVerificationId:
          "Verification code expired, please request a new one",
      StringsKeys.otpSendFailedUseEmail:
          "Failed to send verification code, please try email instead",
      StringsKeys.otpTimeout: "Request timed out, please try again",
      StringsKeys.autoVerificationDone: "Automatically verified",
      StringsKeys.unexpectedErrorTryAgain:
          "An unexpected error occurred, please try again",
    },
  };
}
