// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLJ_0RxrhZ8_xq4ZfqqH3GTqIn93ckF90',
    appId: '1:612566346205:web:350265d3815cc892f46e34',
    messagingSenderId: '612566346205',
    projectId: 'todo-bbca0',
    authDomain: 'todo-bbca0.firebaseapp.com',
    storageBucket: 'todo-bbca0.firebasestorage.app',
    measurementId: 'G-L67DX61FSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Z6I6_fCFBAXocinu-9WLjV0q9-rlSPI',
    appId: '1:612566346205:android:934971bff2d18325f46e34',
    messagingSenderId: '612566346205',
    projectId: 'todo-bbca0',
    storageBucket: 'todo-bbca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTLSladDDET0v1_wsbTHRtDqw8H8uqFsk',
    appId: '1:612566346205:ios:683b158f2af20928f46e34',
    messagingSenderId: '612566346205',
    projectId: 'todo-bbca0',
    storageBucket: 'todo-bbca0.firebasestorage.app',
    iosBundleId: 'com.example.eComerece',
  );
}
